```{r echo=FALSE}
message("Making plots for feature info table...")

allPlots <- vector("character", length(rmdVars$components) * 4)
curPlotInd <- 0
plotPathFull <- getPlotPath(FALSE)
plotPathLink <- getPlotPath(TRUE)

prog <- openProgBar(0, length(rmdVars$fGroups))
allPlots <- lapply(seq_len(length(rmdVars$fGroups)), function(grpi)
{
    path <- file.path(plotPathFull, sprintf("ftinfo_eic_%d.png", grpi))
    makeCachedPlot(path, "plotChroms",
                   list(rmdVars$fGroups[, grpi], rmdVars$EICRtWindow,
                        rmdVars$EICMzExpWindow, rmdVars$retMin,
                        rmdVars$EICTopMost, rmdVars$EICTopMostByRGroup, rmdVars$EICs, colourBy = "rGroup", title = ""),
                   7, 4.5, bg = NA, cacheDB = rmdVars$cacheDB)
    setTxtProgressBar(prog, grpi)
    return(path)
})
close(prog)

if (rmdVars$optimizePng && length(allPlots) > 0)
    optimizePngPlots(allPlots)
```


Feature info {data-orientation=rows}
===

## { .ftInfo }

### Feature info { .ftInfo }

<style> .ftInfo { overflow-x: auto; } </style>

```{r echo=FALSE}
eicpaths <- file.path(plotPathLink, sprintf("ftinfo_eic_%d.png", seq_len(length(rmdVars$fGroups))))

if (rmdVars$selfContained)
    eicpaths <- sapply(eicpaths, knitr::image_uri)

table <- as.data.table(rmdVars$fGroups, qualities = "score", average = TRUE)
table[, EIC := imgTags(eicpaths)]
setcolorder(table, c("group", "EIC"))
if (rmdVars$retMin)
    table[, ret := ret / 60]
for (col in c("ret", "mz")) # UNDONE
    set(table, j = col, value = round(table[[col]], if (col == "mz") 5 else 2))

initDT <- DT::JS("function(settings, json) {",
                 "setTimeout(function() {",
                 "$(\"#ftInfoTable .dataTable\").DataTable().columns.adjust().draw(); }",
                 ", 25); }")
buttonFunc <- function(cols)
{
    cols <- match(cols, names(table))
    DT::JS(paste("function (e, dt, node, config) {",
                 paste0(sprintf("dt.column(%d).visible(!dt.column(%d).visible());", cols, cols), collapse = "\n"),
                 "}"))
}

bts <- list(list(text = "Intensities", action = buttonFunc(replicateGroups(rmdVars$fGroups))))
hiddenCols <- integer()
if (hasFGroupScores(rmdVars$fGroups))
{
    setnames(table, "totalScore", "Total score")
    otherSc <- c(featureScoreNames(), featureGroupScoreNames())
    bts <- c(bts, list(list(text = "Total score", action = buttonFunc("Total score")),
                       list(text = "Other scores", action = buttonFunc(otherSc))))
    hiddenCols <- match(otherSc, names(table))
}

tabOpts <- list(dom = "Bfrtip", scrollX = TRUE, scrollY = "600px", deferRender = TRUE,
                paging = FALSE, autoWidth = TRUE,
                initComplete = initDT, order = list(list(0, "asc")),
                buttons = list(list(extend = "colvis", text = "Columns",
                                    background = FALSE, collectionLayout = "three-column",
                                    buttons = bts)))
if (length(hiddenCols))
    tabOpts <- c(tabOpts, list(columnDefs = list(list(visible = FALSE, targets = hiddenCols))))

DT::datatable(table, extensions = "Buttons", options = tabOpts, elementId = "ftInfoTable", escape = FALSE)
```
