---
title: "report"
author: "`r getPackageName(create = FALSE)`"
date: "`r date()`"
output:
    flexdashboard::flex_dashboard:
        vertical_layout: scroll
        mathjax: null
        fig_mobile: false
        dev: png
---

```{r setup, include=FALSE}
# knitr::knit_hooks$set(optipng = knitr::hook_pngquant)
knitr::knit_hooks$set(pngquant = function(before, options, envir) suppressMessages(knitr::hook_pngquant(before, options, envir)))
knitr::opts_chunk$set(echo = FALSE, fig.keep = "all", fig.retina = 1, dpi = 72)
if (rmdVars$optimizePng)
    knitr::opts_chunk$set(pngquant = "")

# utility funcs for plotting
getPlotPath <- function()
{
    ret <- if (rmdVars$selfContained) "." else file.path(rmdVars$outPath, "report_files", "plots")
    mkdirp(ret)
    return(ret)
}

makePlot <- function(out, w, h, expr)
{
    png(out, w, h, units = "in", res = 72)
    eval(expr)
    dev.off()
}
```

<style>
pre, code {
    white-space: pre !important;
    overflow-x: auto !important;
    max-height: 275px;
    overflow-y: auto;
}
</style>


Summary {data-orientation=rows}
================

## { data-height=350 }

### EICs

```{r obj-plot, fig.width=10, fig.height=4}
par(mai = c(0.9, 0.8, 0.6, 0.1))
plotEIC(rmdVars$fGroups, rmdVars$EICRtWindow, rmdVars$EICMzWindow,
        rmdVars$retMin, 1, rmdVars$EICs, TRUE, FALSE, colourBy = "fGroup", showLegend = FALSE,
        onlyPresent = rmdVars$EICOnlyPresent)
```


## { data-height=300 }

### Objects

```{r obj-show}
objToShow <- list(rmdVars$fGroups, rmdVars$MSPeakLists, rmdVars$formConsensus,
                  rmdVars$compounds, rmdVars$components, rmdVars$cInfo)
objToShow <- objToShow[!sapply(objToShow, is.null)]
for (obji in seq_along(objToShow))
{
    show(objToShow[[obji]])
    cat("\n")
}
```


### Retention vs m/z
```{r fig.height=4}
par(mai = c(0.9, 0.8, 0.1, 0.1))
selectMethod("plot", class(rmdVars$fGroups))(rmdVars$fGroups)
```


```{r}
rGroupLen <- length(unique(analysisInfo(removeEmptyAnalyses(rmdVars$fGroups))$group))
doPlotChord <- length(rmdVars$fGroups) > 0 && rmdVars$reportChord && rGroupLen > 1
doPlotVenn <- length(rmdVars$fGroups) > 0 && rGroupLen > 1 && rGroupLen < 6
doEICs <- length(rmdVars$fGroups) > 0 && rmdVars$reportFGroups
```


`r if (doPlotChord || doPlotVenn) "## { data-height=425 } \n"`

`r if (doPlotChord) "### Chord diagram\n"`
```{r fig.height=5.5, eval=doPlotChord,out.height="400px"}
message("Creating chord diagram... ", appendLF = FALSE)
plotChord(rmdVars$fGroups)
message("Done!")
```

`r if (doPlotVenn) "### Venn diagram\n"`
```{r fig.height=5.5, eval=doPlotVenn}
plotVenn(rmdVars$fGroups)
```


`r if (rmdVars$reportFGroups) "EICs\n===\n"`
```{r eval=doEICs}
message("Plotting EICs...")
prog <- txtProgressBar(0, length(rmdVars$fGroups), style = 3, file = stderr())

for (grpi in seq_len(length(rmdVars$fGroups)))
{
    setTxtProgressBar(prog, grpi)
    plotEIC(rmdVars$fGroups[, grpi], rmdVars$EICRtWindow, rmdVars$EICMzWindow,
            rmdVars$retMin, rmdVars$EICTopMost, rmdVars$EICs, colourBy = "rGroup",
            showLegend = TRUE, onlyPresent = rmdVars$EICOnlyPresent)
}

close(prog)
```


```{r child="components.Rmd", eval=!is.null(rmdVars$components) && length(rmdVars$components) > 0}
```


```{r child="annotation.Rmd", eval=!is.null(rmdVars$compounds) || !is.null(rmdVars$compsCluster) || !is.null(rmdVars$formConsensus) || !is.null(rmdVars$components)}
```

```{r child="cluster.Rmd", eval=!is.null(rmdVars$cInfo)}
```
