---
title: "report"
author: "`r getPackageName(create = FALSE)`"
date: "`r if (!properties$noDate) date() else '' `"
output:
    flexdashboard::flex_dashboard:
        vertical_layout: fill
        mathjax: null
        fig_mobile: false
        dev: svg
        theme:
            version: 3
            bootswatch: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.keep = "all", fig.retina = 1, dpi = 72)

```

<style>
pre, code {
    white-space: pre !important;
    overflow-x: auto !important;
    max-height: 275px;
    overflow-y: auto;
}

/* set positioning to allow scaling: https://stackoverflow.com/a/45144857 */
/* UNDONE: doesn't work...
.svglite {
    position: absolute;
    width: 100%;
    height: auto;
}*/

</style>

Summary {data-orientation=columns}
================

## { data-width=500 }

### Most intense feature of each group 

```{r, results = "asis"}
printf("%s\n\n", plots$overview$chroms)
```

### Retention vs m/z

```{r, results = "asis"}
printf("%s\n\n", plots$overview$retMZ)
```

## { data-width=300 }

### Objects { data-height=100 }

```{r obj-show}
cat(objectsShow)
```


```{r, results = "asis", eval = !is.null(plots$overview$chord) || !is.null(plots$overview$venn) || is.null(plots$overview$UpSet)}
cat("### Feature distribution { data-height=200 }\n\n")
if (!is.null(plots$overview$chord))
    printf("#### Chord diagram\n\n%s\n\n", plots$overview$chord)
if (!is.null(plots$overview$venn))
    printf("#### Venn diagram\n\n%s\n\n", plots$overview$venn)
if (!is.null(plots$overview$UpSet))
    printf("#### UpSet diagram\n\n%s\n\n", plots$overview$UpSet)
```

```{r child="details.Rmd"}
```
