<script>`r readAllFile(system.file("js", "utils-report.js", package = "patRoon"))`</script>

Transformation Products {data-orientation=rows}
===

```{r TPPlots, fig.keep='none'}

# sync objects
components <- rmdVars$components[, intersect(names(rmdVars$fGroups), groupNames(rmdVars$components))]
components <- delete(components, i = !componentInfo(components)$parent_group %chin% names(rmdVars$fGroups))

cInfo <- componentInfo(components)

if (isScreening(rmdVars$fGroups))
{
    suspTbl <- as.data.table(rmdVars$fGroups, collapseSuspects = NULL)
    suspTbl <- suspTbl[, grepl("^susp_|group", names(suspTbl)), with = FALSE]
    setnames(suspTbl, sub("^susp_", "", names(suspTbl)))
}

plotPathFull <- getPlotPath(FALSE)

message("Generating parent plots...")
prog <- openProgBar(0, nrow(cInfo))

makeStructPlot <- function(SMI, out)
{
    mol <- getMoleculesFromSMILES(SMI, emptyIfFails = TRUE)[[1]]
    withr::with_png(out, width = 1.5, height = 1.5, units = "in", res = 72, bg = NA, code = {
        withr::with_par(list(mar = rep(0, 4)), plot(getRCDKStructurePlot(mol, 150, 150)))
    })
}

plotIntMainArgs <- list(average = TRUE)
if (isFGSet(rmdVars$fGroups))
{
    plotIntMainArgs <- c(plotIntMainArgs, list(sets = TRUE))
} else
{
    plotIntMainArgs <- c(plotIntMainArgs, list(col = "black"))
}

parentPlots <- setNames(Map(split(cInfo, seq_len(nrow(cInfo))), seq_len(nrow(cInfo)), f = function(parentRow, i)
{
    grpi <- match(parentRow$parent_group, names(rmdVars$fGroups))
    plots <- list()
    fg <- rmdVars$fGroups[, parentRow$parent_group]
    
    plots[["int"]] <- file.path(plotPathFull, sprintf("int-parent_%d.png", grpi))
    makeCachedPlot(plots[["int"]], "plotInt", c(list(fg), plotIntMainArgs), 3.3, 3.3,
                   bg = NA, cacheDB = rmdVars$cacheDB)

    if (!is.null(parentRow[["parent_SMILES"]]))
    {
        plots[["struct"]] <- file.path(plotPathFull, sprintf("struct-parent_%d.png", grpi))
        makeStructPlot(parentRow$parent_SMILES, plots[["struct"]])
    }

    setTxtProgressBar(prog, i)
    
    return(plots)
}), cInfo$name)

message("Generating TP plots...")
prog <- openProgBar(0, length(components))
cmpTab <- as.data.table(components)
# isFGScrAnnotated <- isScreening(rmdVars$fGroups) && screenInfo(rmdVars$fGroups)[[""]]

TPPlotName <- function(cmp, grp) paste0(cmp, "_", grp)

TPPlots <- setNames(Map(split(cmpTab, seq_len(nrow(cmpTab))), seq_len(nrow(cmpTab)), f = function(ctRow, i)
{
    grpi <- match(ctRow$group, names(rmdVars$fGroups))
    plots <- list()
    fg <- rmdVars$fGroups[, ctRow$group]
    
    plots[["int"]] <- file.path(plotPathFull, sprintf("int-TP_%d.png", grpi))
    makeCachedPlot(plots[["int"]], "plotInt", c(list(fg), plotIntMainArgs), 3.3, 3.3, bg = NA,
                   cacheDB = rmdVars$cacheDB)

    SMI <- ctRow[["SMILES"]]
    if (!is.null(SMI))
    {
        plots[["struct"]] <- file.path(plotPathFull, sprintf("struct-parent_%d.png", grpi))
        makeStructPlot(SMI, plots[["struct"]])
    }
    
    if (!is.null(rmdVars[["MSPeakLists"]]))
    {
        # try to plot a mirror spectrum: use compounds if possible, otherwise try formulas or finally peak lists
        plSpecArgs <- list()
        
        if (isScreening(rmdVars$fGroups))
        {
            suspParRow <- suspTbl[name == ctRow$parent_name & group == ctRow$parent_group]
            suspTPRow <- suspTbl[name == ctRow$TP_name & group == ctRow$group]
            if (!is.null(rmdVars[["compounds"]]) && !is.null(suspTbl[["compRank"]]) &&
                all(c(ctRow$parent_group, ctRow$group) %chin% groupNames(rmdVars$compounds)) &&
                nrow(suspTPRow) == 1 && !is.na(suspParRow$compRank) && !is.na(suspTPRow$compRank))
            {
                plSpecArgs <- list(obj = rmdVars$compounds, formulas = rmdVars[["formulas"]],
                                   index = c(suspParRow$compRank, suspTPRow$compRank),
                                   MSPeakLists = rmdVars$MSPeakLists, plotStruct = FALSE)
            }
            else if (!is.null(rmdVars[["formulas"]]) && !is.null(suspTbl[["formRank"]]) &&
                     all(c(ctRow$parent_group, ctRow$group) %chin% groupNames(rmdVars$formulas)) &&
                     nrow(suspTPRow) == 1 && !is.na(suspParRow$formRank) && !is.na(suspTPRow$formRank))
            {
                plSpecArgs <- list(obj = rmdVars$formulas, precursor = c(suspParRow$formula, suspTPRow$formula),
                                   MSPeakLists = rmdVars$MSPeakLists)
            }
        }
        
        if (length(plSpecArgs) == 0 && !is.null(rmdVars$MSPeakLists[[ctRow$parent_group]][["MSMS"]]) &&
            !is.null(rmdVars$MSPeakLists[[ctRow$group]][["MSMS"]]))
        {
            # no formulas/compounds, try peak lists
            plSpecArgs <- list(obj = rmdVars$MSPeakLists, MSLevel = 2)
        }
        
        if (length(plSpecArgs) > 0)
        {
            plots[["spec"]] <- file.path(plotPathFull, sprintf("spec-sim_%d.png", grpi))
            makeCachedPlot(plots[["spec"]], "plotSpectrum", c(plSpecArgs, list(groupName = c(ctRow$parent_group, ctRow$group),
                                                                               specSimParams = rmdVars$specSimParams, title = "")),
                           5, 4.5, bg = NA, cacheDB = rmdVars$cacheDB)
        }
    }
    
    setTxtProgressBar(prog, i)
    
    return(plots)
}), TPPlotName(cmpTab$name, cmpTab$group))

prepPlots <- function(pl)
{
    ap <- unlist(allPlots); ap <- ap[nzchar(ap)]
    if (rmdVars$optimizePng && length(ap > 0))
        optimizePngPlots(ap)
    
    if (rmdVars$selfContained)
        pl <- rapply(pl, function(ap) sapply(ap, function(p) if (nzchar(p)) knitr::image_uri(p) else ""), how = "replace")
    return(pl)
}

parentPlots <- prepPlots(parentPlots); TPPlots <- prepPlots(TPPlots)
```


##
    
### Parents { data-width=400 .parents }
    
<style> .parents { overflow-x: auto; } </style>
    
```{r echo=FALSE}
makeTPTab <- function(cr, cols)
{
    allCols <- unique(unlist(lapply(cols, function(cl) grep(paste0("^", cl), names(cr), value = TRUE))))
    
    roundCols <- function(t) t[, (names(t)) := lapply(.SD, function(x) if (is.double(x)) round(x, 2) else x)]
    
    if (!isTRUE(all.equal(cols, allCols, check.attributes = FALSE)))
    {
        sets <- unique(sub(".+\\-(.+)$", "\\1", allCols[grepl("-", allCols, fixed = TRUE)]))
        
        # NOTE: " " (a space) results in an unnamed column
        
        ret <- rbindlist(lapply(c(" ", sets), function(s)
        {
            takeCols <- if (s == " ") cols else paste0(cols, "-", s)
            whCols <- which(takeCols %in% names(cr))
            if (length(whCols) == 0)
                return(data.table())
            
            t <- cr[, takeCols[whCols], with = FALSE]
            setnames(t, cols[whCols])
            
            t <- roundCols(t)
            
            t[, set := s]
            setcolorder(t, "set")
            
            return(t)
        }), fill = TRUE)
        ret <- transpose(ret, keep.names = " ", make.names = "set")
    }
    else
    {
        ret <- roundCols(cr[, cols, with = FALSE])
        ret <- setnames(transpose(ret, keep.names = " "), 2, "value")
    }
    
    return(knitr::kable(ret, "html", escape = FALSE) %>%
               kableExtra::kable_styling(font_size = 11) %>%
               kableExtra::scroll_box(extra_css = "overflow-x: auto;"))

}

chromPlotStyle <- "width: auto; height: 250px;"

parentsDT <- data.table(compInd = seq_len(nrow(cInfo)))

splitCI <- split(cInfo, seq_len(nrow(cInfo)))

parentInfoCols <- intersect(c("name", "parent_name", "parent_group", "parent_formula", "parent_CID"), names(cInfo))
parentsDT[, parent := sapply(splitCI, function(cir)
{
    parInfo <- cir[, parentInfoCols, with = FALSE]
    setnames(parInfo, sub("^parent_", "", names(parInfo)))
    
    if (!is.null(parInfo[["formula"]]))
        parInfo[, formula := subscriptFormulaHTML(formula)]
    if (!is.null(parInfo[["CID"]]))
        parInfo[, CID := makeDBIdentLink("pubchem", CID)]

    par <- makeInfoBox(paste0(names(parInfo), ": ", parInfo, collapse = "<br>"))
    
    if (!is.null(parentPlots[[cir$name]][["struct"]]))
        par <- paste0(imgTags(parentPlots[[cir$name]][["struct"]]), "<br>", par)
    
    return(par)
})]

parentsDT[, EIC := imgTags(chromPaths[match(cInfo$parent_group, names(rmdVars$fGroups))], style = chromPlotStyle)]

if (isScreening(rmdVars$fGroups))
{
    suspCols <- c("formRank", "compRank", "annSimBoth", "estIDLevel")
    if (any(sapply(suspCols, grepl, names(suspTbl))))
    {
        parentsDT[, screening := sapply(splitCI, function(cir)
        {
            sr <- suspTbl[name == cir$parent_name & group == cir$parent_group]
            if (nrow(sr) > 0)
                makeTPTab(sr, suspCols)
            else
                ""
        })]
    }
}

parentsDT[, "intensity profile" := imgTags(sapply(parentPlots[cInfo$name], "[[", "int"))]

parentsDT[, show := { sprintf("<button onclick=\"showTPs('%s', %d);\" style=\"padding: 0px 3px 0px 3px\">Show</button>",
                              compInd, match(cInfo$parent_group, names(rmdVars$fGroups))) }]
setcolorder(parentsDT, c("compInd", "show"))

DT::datatable(parentsDT,
              extensions = "Buttons",
              options = list(paging = FALSE, pageLength = -1, scrollX = TRUE, scrollY = "300px",
                             dom = "tip",
                             initComplete = DT::JS("function(settings, json)",
                                                   "{ setTimeout(initTPs, 25); }"),
                             order = list(list(0, "asc")),
                             columnDefs = list(list(visible = FALSE, targets = 0),
                                               list(className = "dt-center",
                                                    targets = (seq_len(ncol(parentsDT)))-1))),
              escape = FALSE, rownames = FALSE, elementId = "parentsTable")
```


##

### Transformation Products { .TPsClass }

<style> .TPsClass { overflow-x: auto; } </style>
    
```{r echo=FALSE}

cTable <- componentTable(components)

TPsDT <- rbindlist(Map(cTable, seq_along(cTable), names(cTable), f = function(cmp, cInd, cName)
{
    ret <- data.table(compInd = cInd, "#" = seq_len(nrow(cmp)))
    
    splitCmp <- split(cmp, seq_len(nrow(cmp)))
    
    trCols <- intersect(c("formula", "retDir", "TP_retDir", "retDiff", "mzDiff", "formulaDiff", "set", "CID"),
                        names(cmp))
    ret[, TP := sapply(splitCmp, function(cr)
    {
        tpInfo <- cr[, c("TP_name", "group", trCols), with = FALSE]
        if (rmdVars$retMin)
            tpInfo[, retDiff := retDiff / 60]
        tpInfo[, c("retDiff", "mzDiff") := .(round(retDiff, 2), round(mzDiff, 5))]
        setnames(tpInfo, "TP_name", "name")
        
        if (!is.null(tpInfo[["retDir"]]) && !is.null(tpInfo[["TP_retDir"]]))
        {
            tpInfo[, "retDir (predicted/actual)" := paste0(TP_retDir, "/", retDir)]
            tpInfo[, c("retDir", "TP_retDir") := NULL]
        }
        if (!is.null(tpInfo[["formula"]]))
            tpInfo[, formula := subscriptFormulaHTML(formula)]
        if (!is.null(tpInfo[["formulaDiff"]]))
            tpInfo[, formulaDiff := subscriptFormulaHTML(formulaDiff)]
        if (!is.null(tpInfo[["CID"]]))
            tpInfo[, CID := makeDBIdentLink("pubchem", CID)]
        
        tp <- makeInfoBox(paste0(names(tpInfo), ": ", tpInfo, collapse = "<br>"))
        
        if (!is.null(TPPlots[[TPPlotName(cName, cr$group)]][["struct"]]))
            tp <- paste0(imgTags(TPPlots[[TPPlotName(cName, cr$group)]][["struct"]]), "<br>", tp)
        
        return(tp)
    })]
    
    ret[, EIC := imgTags(chromPaths[match(cmp$group, names(rmdVars$fGroups))], style = chromPlotStyle)]
    
    if (isScreening(rmdVars$fGroups))
    {
        suspCols <- c("formRank", "compRank", "annSimBoth", "estIDLevel")
        if (any(sapply(suspCols, grepl, names(suspTbl))))
        {
            ret[, screening := sapply(splitCmp, function(cr)
            {
                sr <- suspTbl[name == cr$TP_name & group == cr$group]
                if (nrow(sr) > 0)
                    makeTPTab(sr, suspCols)
                else
                    ""
            })]
        }
    }
    
    if (any(grepl("^(specSimilarity|fragmentMatches|neutralLossMatches)", names(cmp))))
    {
        ret[, similarity := sapply(splitCmp, function(cr)
        {
            simt <- makeTPTab(cr, c("specSimilarity", "specSimilarityPrec", "specSimilarityBoth",
                                    "fragmentMatches", "neutralLossMatches"))
            return(simt)
        })]
    }
    
    ret[, spectrum := sapply(splitCmp, function(cr)
    {
        if (!is.null(TPPlots[[TPPlotName(cName, cr$group)]][["spec"]]))
            return(paste0(imgTags(TPPlots[[TPPlotName(cName, cr$group)]][["spec"]])))
        return("")
    })]
    if (!any(nzchar(ret$spectrum)))
        set(ret, j = "spectrum", value = NULL)

    ret[, "intensity profile" := imgTags(sapply(TPPlots[TPPlotName(cName, cmp$group)], "[[", "int"))]
    return(ret)
}))

DT::datatable(TPsDT, options = list(scrollX = TRUE, scrollY = "600px", deferRender = TRUE,
                                    dom = "Blrtp", pageLength = 25, autoWidth = TRUE,
                                    ordering = FALSE,
                                    columnDefs = list(list(visible = FALSE, targets = 0),
                                                      list(className = "dt-center",
                                                           targets = (seq_len(ncol(TPsDT)))-1)),
                                    buttons = list(list(extend = "colvis", background = FALSE,
                                                        columns = seq(3, ncol(TPsDT)-1)))),
              rownames = FALSE, escape = FALSE, elementId = "TPsTable")
```

