#' @section Source: Subscripting of formulae for plots generated by
#'   \code{plotSpectrum} is based on the \code{chemistry2expression} function
#'   from the \href{https://github.com/schymane/ReSOLUTION}{ReSOLUTION} package.
