#' @param parents The parents for which transformation products should be obtained. This can be \itemize{
#'
#'   \item a suspect list (see \link[=suspect-screening]{suspect screening} for more information)
#'
#'   \item the output of \code{\link{screenSuspects}} in which case the suspects hits are used as parents
#'
#'   <%= if (exists("parComp")) "\\item a \\code{\\link{compounds}} object in which case all candidates are used
#'   parents" %>
#'
#'   <%= if (exists("parNULL")) "\\item \\code{NULL} in which case all parents from the library are used." %>
#'
#'   }
#'
#'   The parents need to have <%= req %> information available.
#' @param skipInvalid If set to \code{TRUE} then the parents will be skipped (with a warning) for which insufficient
#'   information (\emph{e.g.} SMILES) is available.
#'
#' <%= if (exists("neutTPs")) "@param neutralizeTPs If \\code{TRUE} then all resulting TP structure information is
#' neutralized. This argument has a similar meaning as \\code{neutralChemProps}. This is defaulted to \\code{TRUE} for
#' prediction algorithms, as these may output charged molecules. \\strong{NOTE:} if neutralization results in
#' duplicate TPs, \\emph{i.e.} when the neutral form of the TP was also generated by the algorithm, then the
#' neutralized TP \\emph{will be removed}." %>
#'
#' <%= if (exists("parComp")) "@note When the \\code{parents} argument is a \\code{\\link{compounds}} object, the
#' candidate library \\code{identifier} is used in case the candidate has no defined \\code{compoundName}." %>
