```{r setup, include = FALSE}

# otherwise Linux will get into memory troubles...
knitr::knit_meta("latex_dependency", clean = TRUE)

knitr::opts_chunk$set(
  collapse = FALSE,
  comment = "#>",
  fig.width = 6, fig.height = 4, out.width = "50%",
  warning = FALSE, message = FALSE
)

options(patRoon.cache.fileName = "~/tutorial.sqlite")
options(patRoon.progress.opts = list(style = 1, width = 80))
options(width=1500) # big nr to avoid wrapping text in code chunks
options(datatable.print.nrows = 15)

# pkgdown doesn't seem to load RProfile, which may become annoying when MetFrag
# path's and other patRoon settings are set there...
if (pkgdown::in_pkgdown() && file.exists("~/.Rprofile"))
  source("~/.Rprofile")

library(patRoon)

runData <- TRUE
if (runData)
{
    # try to sync with tutorial so cache can be re-used
    anaInfo <- generateAnalysisInfo(paths = patRoonData::exampleDataPath(),
                                    groups = c(rep("solvent", 3), rep("standard", 3)),
                                    blanks = "solvent")
    anaInfoRG <- generateAnalysisInfo(paths = patRoonData::exampleDataPath(),
                                      groups = c(rep("repl1", 2),
                                                 rep("repl2", 2),
                                                 rep("repl3", 1),
                                                 rep("repl4", 1)))
    
    fList <- findFeatures(anaInfo, "openms")
    fGroups <- fGroupsUF <- groupFeatures(fList, "openms")
    fGroups <- filter(fGroups, preAbsMinIntensity = 100, absMinIntensity = 10000,
                      relMinReplicateAbundance = 1, maxReplicateIntRSD = 0.75,
                      blankThreshold = 5, removeBlanks = TRUE,
                      retentionRange = c(120, Inf), mzRange = NULL)

    fListRG <- findFeatures(anaInfoRG, "openms")
    fGroupsRG <- groupFeatures(fListRG, "openms")
    fGroupsRG <- filter(fGroupsRG, preAbsMinIntensity = 100, absMinIntensity = 10000)
    
    anaInfoConc <- generateAnalysisInfo(paths = patRoonData::exampleDataPath(),
                                        groups = c(rep("solvent", 3), rep("standard", 3)),
                                        blanks = "solvent",
                                        concs = c(NA, NA, NA, 1, 2, 3))
    fListConc <- findFeatures(anaInfoConc, "openms")
    fGroupsConc <- groupFeatures(fListConc, "openms")
    fGroupsConc <- filter(fGroupsConc, preAbsMinIntensity = 100, absMinIntensity = 10000,
                          relMinReplicateAbundance = 1, maxReplicateIntRSD = 0.75,
                          blankThreshold = 5, removeBlanks = TRUE,
                          retentionRange = c(120, Inf), mzRange = NULL)
        
    avgPListParams <- getDefAvgPListParams(clusterMzWindow = 0.002)
    mslists <- generateMSPeakLists(fGroups, "mzr", maxMSRtWindow = 5, precursorMzWindow = 4,
                                   avgFeatParams = avgPListParams, avgFGroupParams = avgPListParams)
    mslists <- filter(mslists, relMSMSIntThr = 0.02, topMSMSPeaks = 10)
    formulas <- generateFormulas(fGroups, "genform", mslists, relMzDev = 5,
                                 adduct = "[M+H]+", elements = "CHNOPSCl",
                                 calculateFeatures = TRUE, featThreshold = 0.75)
    compsMF <- compounds <-
        generateCompounds(fGroups, mslists, "metfrag", method = "CL",
                          dbRelMzDev = 5, fragRelMzDev = 5, fragAbsMzDev = 0.002,
                          adduct = "[M+H]+", database = "pubchem", maxCandidatesToStop = 5000)
    compsSIR <- generateCompounds(fGroups, mslists, "sirius")
    
    componCAM <- components <- generateComponents(fGroups, "camera", ionization = "positive")
    componInt <- generateComponents(fGroupsRG, "intclust")
    componNT <- generateComponents(fGroupsUF, "nontarget", extraOpts = list(minlength=3), ionization = "positive")
    
    compsClust <- makeHCluster(compsMF)
    
    pSet <- generateFeatureOptPSet("openms")
    ftOpt <- optimizeFeatureFinding(anaInfo[1:2,], "openms", pSet,
                                    paramRanges = list(noiseThrInt = c(500, Inf)))
    
    # saveRDS(list(fList = fList, fGroups = fGroups, fGroupsUF = fGroupsUF, fListRG = fListRG,
    #              fGroupsRG = fGroupsRG, mslists = mslists, formulas = formulas, compsMF = compsMF,
    #              compsSIR = compsSIR, componCAM = componCAM, componInt = componInt, componNT = componNT,
    #              compsClust = compsClust,
    #              ftOpt = ftOpt),
    #         "~/handbook-obj.Rds")
}
```

```{css code=readLines(file.path(vignDir, "styles.css")),echo=FALSE,eval=knitr::is_html_output()}
```

```{r child=file.path(vignDir, "shared", "_refs.Rmd")}
```
