# SPDX-FileCopyrightText: 2016-2026 Rick Helmus <r.helmus@uva.nl>
#
# SPDX-License-Identifier: GPL-3.0-only

#' @include main.R
#' @include compounds.R
#' @include utils-sirius.R
#' @include feature_groups-set.R
NULL

#' Compounds class for SIRIUS results.
#'
#' This class is derived from \code{\link{compounds}} and contains additional specific \command{SIRIUS} data.
#'
#' Objects from this class are generated by \code{\link{generateCompoundsSIRIUS}}
#'
#' @slot fingerprints A \code{list} with for each feature group result a \code{data.table} containing fingerprints
#'   obtained with \command{CSI:FingerID}.
#'   \strong{NOTE:} not yet implemented.
#'
#' @templateVar class compoundsSIRIUS
#' @template class-hierarchy
#'
#' @seealso \code{\link{compounds}} and \code{\link{generateCompoundsSIRIUS}}
#'
#' @inherit generateCompoundsSIRIUS references
#'
#' @export
compoundsSIRIUS <- setClass("compoundsSIRIUS", slots = c(fingerprints = "list"),
                            contains = "compounds")


#' @rdname compounds-class
#' @export
setMethod("delete", "compoundsSIRIUS", function(obj, i = NULL, j = NULL, ...)
{
    obj <- callNextMethod()
    return(syncSIRFPs(obj))
})

#' @rdname pred-quant
#' @export
setMethod("predictRespFactors", "compoundsSIRIUS", function(obj, fGroups, calibrants, eluent, organicModifier, pHAq,
                                                            concUnit = "ugL", calibConcUnit = concUnit, type = "FP")
{
    checkPackage("MS2Quant", "kruvelab/MS2Quant")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    assertQuantEluent(eluent, fGroups, add = ac)
    checkmate::assertChoice(organicModifier, c("MeOH", "MeCN"), add = ac)
    checkmate::assertNumber(pHAq, finite = TRUE, add = ac)
    aapply(assertConcUnit, . ~ concUnit + calibConcUnit, fixed = list(add = ac))
    checkmate::assertChoice(type, c("FP", "SMILES", "both"), add = ac)
    checkmate::reportAssertions(ac)
    
    if (type != "SMILES")
    {
        stop("predictRespFactors() with SIRIUS fingerprints is not working, since MS2Quant is incompatible with SIRIUS 6.0",
             call. = FALSE)
    }
    
    if (type == "SMILES" || type == "both")
        obj <- callNextMethod(obj, fGroups = fGroups, calibrants = calibrants, eluent = eluent,
                              organicModifier = organicModifier, pHAq = pHAq, concUnit = concUnit,
                              calibConcUnit = calibConcUnit, updateScore = FALSE, scoreWeight = 1)

    calibrants <- assertAndPrepareQuantCalib(calibrants, calibConcUnit)
    
    if (length(obj) == 0)
        return(obj)
    
    if (type == "FP" || type == "both")
    {
        printf("Predicting response factors from fingerprints with MS2Quant for %d candidates...\n", length(obj))
        res <- predictRespFactorsSIRFPs(obj, groupInfo(fGroups), calibrants, eluent, organicModifier, pHAq, concUnit)
        obj@MS2QuantMeta <- res$MD
        
        obj@groupAnnotations <- Map(groupNames(obj), annotations(obj), f = function(grp, ann)
        {
            ann <- copy(ann)
            if (nrow(res$RFs) == 0)
            {
                ann[, RF_SIRFP := NA_real_]
                return(ann)
            }
        
            if (!is.null(ann[["RF_SIRFP"]]))
                ann[, RF_SIRFP := NULL] # clearout for merge below    
            return(merge(ann, res$RFs[group == grp, c("neutral_formula", "RF_SIRFP"), with = FALSE],
                         by = "neutral_formula", sort = FALSE, all.x = TRUE))
        })
        
        obj <- addCompoundScore(obj, "RF_SIRFP", FALSE, 1)
    }
    
    return(obj)
})

#' @rdname pred-tox
#' @export
setMethod("predictTox", "compoundsSIRIUS", function(obj, type = "FP", LC50Mode = "static", concUnit = "ugL")
{
    checkPackage("MS2Tox", "kruvelab/MS2Tox")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertChoice(type, c("FP", "SMILES", "both"), add = ac)
    checkmate::assertChoice(LC50Mode, c("static", "flow"), add = ac)
    assertConcUnit(concUnit, add = ac)
    checkmate::reportAssertions(ac)
    
    if (type != "SMILES")
    {
        stop("predictTox() with SIRIUS fingerprints is not working, since MS2Tox is incompatible with SIRIUS 6.0",
             call. = FALSE)
    }
    
    if (type == "SMILES" || type == "both")
        obj <- callNextMethod(obj, LC50Mode = LC50Mode, concUnit = concUnit, updateScore = FALSE, scoreWeight = 1)
    
    if (length(obj) == 0)
        return(obj)
    
    if (type == "FP" || type == "both")
    {
        printf("Predicting LC50 values from fingerprints with MS2Tox for %d candidates...\n", length(obj))
        LC50Tab <- predictLC50SIRFPs(obj, LC50Mode, concUnit = concUnit)
        
        obj@groupAnnotations <- Map(groupNames(obj), annotations(obj), f = function(grp, ann)
        {
            ann <- copy(ann)
            if (nrow(LC50Tab) == 0)
            {
                ann[, LC50_SIRFP := NA_real_]
                return(ann)
            }

            if (!is.null(ann[["LC50_SIRFP"]]))
                ann[, LC50_SIRFP := NULL] # clearout for merge below    
            return(merge(ann, LC50Tab[group == grp, c("neutral_formula", "LC50_SIRFP"), with = FALSE],
                         by = "neutral_formula", sort = FALSE, all.x = TRUE))
        })
        
        obj <- addCompoundScore(obj, "LC50_SIRFP", FALSE, 1)
    }
    
    return(obj)
})


#' Compound annotation with SIRIUS
#'
#' Uses \href{https://bright-giant.com/sirius-features/}{SIRIUS} for compound annotation.
#'
#' @templateVar algo SIRIUS
#' @templateVar do generate compound candidates
#' @templateVar generic generateCompounds
#' @templateVar algoParam sirius
#' @template algo_generator
#'
#' @details Similar to \code{\link{generateFormulasSIRIUS}}, candidate formulae are generated with SIRIUS. These results
#'   are then fed to \command{CSI:FingerID} to acquire candidate structures. Candidate formulae without any assigned
#'   structure will be removed (unlike \code{\link{generateFormulasSIRIUS}}). This method requires the availability of
#'   MS/MS data, and feature groups without will be ignored.
#'
#' @param verbose If \code{TRUE} then more output is shown in the terminal.
#'
#' @template sirius-args
#' @template adduct-arg
#' @template comp_algo-args
#' @template specSimParams_annSim-arg
#' @template minIMSSpecSim-arg
#'
#' @inheritParams generateCompounds
#'
#' @return A \code{\link{compoundsSIRIUS}} object.
#'
#' @templateVar what generateCompoundsSIRIUS
#' @template main-rd-method
#' @export
setMethod("generateCompoundsSIRIUS", "featureGroups", function(fGroups, MSPeakLists,
                                                               specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                                               adduct = NULL, config = NULL, login = "check",
                                                               alwaysLogin = FALSE, minIMSSpecSim = 0,
                                                               projectPath = NULL, runMode = "execute", SIRIUSAPI = NULL,
                                                               SIRIUSPath = NULL, verbose = TRUE)
{
    # UNDONE: error handling for SIRIUS API calls
    # UNDONE: add fingerprints
    # UNDONE: handle IMSSpecSims: test (including caching)
    # UNDONE: add database column --> once links are fixed and once configs are defined
    # UNDONE: replace SIRIUSPath by patRoonExt
    # UNDONE: doc that login means accepting terms?
    # UNDONE: re-add topMost argument
    
    checkPackage("RSirius", "sirius-ms/sirius-client-openAPI", ghSubDir = "client-api_r/generated")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(MSPeakLists, "MSPeakLists", add = ac)
    assertSpecSimParams(specSimParams, add = ac)
    checkmate::assertR6(config, null.ok = TRUE, add = ac)
    assertSIRIUSLogin(login, add = ac)
    checkmate::assertFlag(alwaysLogin, add = ac)
    checkmate::assertNumber(minIMSSpecSim, lower = 0, finite = TRUE, add = ac)
    checkmate::assert(
        checkmate::checkPathForOutput(projectPath, overwrite = TRUE, extension = "sirius"),
        checkmate::checkNull(projectPath),
        .var.name = "projectPath", add = ac
    )
    checkmate::assertChoice(runMode, c("execute", "read"), add = ac)
    checkmate::assertClass(SIRIUSAPI, "rsirius_api", null.ok = TRUE, add = ac)
    checkmate::assertFlag(verbose, add = ac)
    checkmate::reportAssertions(ac)
    
    if (length(fGroups) == 0)
        return(compoundsSIRIUS6(algorithm = "sirius6"))
    
    adduct <- checkAndToAdduct(adduct, fGroups)
    
    IMSSpecSims <- getIMSFeatAnnSpecSims(MSPeakLists, fGroups, minIMSSpecSim, specSimParams)
    
    if (verbose)
        printf("Processing %d feature groups with SIRIUS+CSI:FingerID...\n", length(fGroups))

    SIRResults <- runSIRIUS(runMode, fGroups, MSPeakLists, IMSSpecSims, adduct, SIRIUSAPI, SIRIUSPath, projectPath,
                            config, login, alwaysLogin, formulasOnly = FALSE, calculateFeatures = FALSE,
                            cacheName = "compoundsSIRIUS")    

    prepRes <- function(res)
    {
        tab <- res$structCands
        if (nrow(tab) == 0)
            return(NULL)
        
        # add in formula info
        colsRename <- setdiff(names(res$formCands), c("formulaId", "fragInfo", "explainedPeaks"))
        setnames(res$formCands, colsRename, paste0("formula_", colsRename))
        tab <- merge(tab, res$formCands, by = "formulaId", sort = FALSE)
        
        tab <- removeDTColumnsIfPresent(tab, "formulaId")
        
        return(tab)
    }
    
    compTabs <- pruneList(sapply(SIRResults, prepRes, simplify = FALSE))

    scRanges <- sapply(compTabs, \(ct) list(score = range(ct$score)), simplify = FALSE)
    
    if (verbose)
    {
        ngrp <- length(compTabs)
        printf("Assigned %d compounds to %d feature groups (%.2f%%).\n", sum(sapply(compTabs, nrow)),
               ngrp, if (length(fGroups) == 0) 0 else ngrp * 100 / length(fGroups))
    }
    
    return(compoundsSIRIUS(groupAnnotations = compTabs, scoreTypes = "score", scoreRanges = scRanges,
                           algorithm = "sirius", MSPeakLists = MSPeakLists, specSimParams = specSimParams,
                           IMSSpecSims = IMSSpecSims, gNames = names(fGroups)))
})

#' @template featAnnSets-gen_args
#' @rdname generateCompoundsSIRIUS
#' @export
setMethod("generateCompoundsSIRIUS", "featureGroupsSet", function(fGroups, MSPeakLists,
                                                                  specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                                                  adduct = NULL, config = NULL, login = "check",
                                                                  alwaysLogin = FALSE, minIMSSpecSim = 0,
                                                                  projectPath = NULL, ..., setThreshold = 0,
                                                                  setThresholdAnn = 0, setAvgSpecificScores = FALSE)
{
    checkmate::assertCharacter(projectPath, len = length(sets(fGroups)), null.ok = TRUE)
    sa <- if (!is.null(projectPath)) lapply(projectPath, function(p) list(projectPath = p)) else list()
    generateCompoundsSet(fGroups, MSPeakLists, specSimParams, adduct, generateCompoundsSIRIUS, config = config,
                         login = login, alwaysLogin = alwaysLogin, minIMSSpecSim = minIMSSpecSim, ...,
                         setThreshold = setThreshold, setThresholdAnn = setThresholdAnn,
                         setAvgSpecificScores = setAvgSpecificScores, setArgs = sa)
})

#' @export
getSIRIUSConfig <- function(config = NULL, import = NULL, login = "check", alwaysLogin = FALSE, SIRIUSAPI = NULL,
                            SIRIUSPath = NULL)
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assert(
        checkmate::checkString(config, min.chars = 1),
        checkmate::checkList(config),
        checkmate::checkScalarNA(config),
        checkmate::checkNull(config),
        .var.name = "config", add = ac
    )
    if (!is.null(import))
        checkmate::assertFileExists(import, add = ac)
    assertSIRIUSLogin(login, add = ac)
    checkmate::assertFlag(alwaysLogin, add = ac)
    checkmate::assertClass(SIRIUSAPI, "rsirius_api", null.ok = TRUE, add = ac)
    checkmate::reportAssertions(ac)
    
    if (!is.null(config) && !is.null(import))
        stop("Only one of 'config' and 'import' can be provided.", call. = FALSE)
    
    if (is.null(SIRIUSAPI))
        SIRIUSAPI <- startSIRIUS(SIRIUSPath)
    
    doSIRIUSLogin(login, alwaysLogin, SIRIUSAPI)

    if (!is.null(config) && is.na(config))
        return(unlist(SIRIUSAPI$jobs_api$GetJobConfigNames()))

    if (!is.null(import))
    {
        config <- RSirius::JobSubmission$new()
        config$validateJSON(import)
        config$fromJSON(import)
    }
    else if (is.null(config))
        config <- SIRIUSAPI$jobs_api$GetDefaultJobConfig(include_config_map = FALSE)
    else if (is.character(config))
        config <- SIRIUSAPI$jobs_api$GetJobConfig(config)

    return(config)
}
