#' @include main.R
#' @include components.R
NULL

genIntComponents <- function(cutClusters, gInfo)
{
    clinds <- seq_along(unique(cutClusters))
    comps <- lapply(clinds, function(ci)
    {
        gNames <- rownames(gInfo)[cutClusters == ci]
        return(data.table(group = gNames, ret = gInfo[gNames, "rts"], mz = gInfo[gNames, "mzs"],
                          intensity = 1))
    })
    names(comps) <- paste0("CMP", seq_along(clinds))
    return(comps)
}

genIntComponentInfo <- function(cutClusters)
{
    clinds <- seq_along(unique(cutClusters))
    return(data.table(name = paste0("CMP", seq_along(clinds)),
                      size = sapply(clinds, function(ci) sum(cutClusters == ci))))
}

#' Components based on clustered intensity profiles.
#'
#' This class is derived from \code{\link{components}} and is used to store
#' hierarchical clustering information from intensity profiles of feature
#' groups.
#'
#' Objects from this class are generated by
#' \code{\link{generateComponentsIntClust}}
#'
#' @slot clusterm Numeric matrix with normalized feature group intensities that
#'   was used for clustering.
#' @slot distm Distance matrix that was used for clustering (obtained with
#'   \code{\link{daisy}}).
#' @slot clust Object returned by \code{\link{hclust}}.
#' @slot cutClusters A \code{list} with assigned clusters (same format as what
#'   \code{\link{cutree}} returns).
#' @slot gInfo The \code{\link{groupInfo}} of the feature groups object that was
#'   used.
#' @slot properties A list containing general properties and parameters used for
#'   clustering.
#'
#' @param x,obj A \code{componentsIntClust} object.
#' @param \dots Further options passed to \code{\link{heatmap}} /
#'   \code{\link{d3heatmap}} (\code{drawHeatMap}), \code{\link{plot.dendrogram}}
#'   (\code{plot}) or \code{\link[graphics]{plot}} (\code{plotInt}).
#'
#' @references \insertRef{Scholle2018}{patRoon}
#'
#' @seealso \code{\link{components}} and \link{component-generation}
#'
#' @note The intensity values for components (used by \code{plotSpec}) are set
#'   to a dummy value (1) as no single intensity value exists for this kind of
#'   components.
#' @export
componentsIntClust <- setClass("componentsIntClust",
                               slots = c(clusterm = "matrix", distm = "dissimilarity", clust = "hclust",
                                         cutClusters = "numeric", gInfo = "data.frame", properties = "list"),
                               contains = "components")


#' @describeIn componentsIntClust Accessor method to the \code{clust} slot,
#'   which was generated by \code{\link{hclust}}.
#' @export
setMethod("clusters", "componentsIntClust", function(obj) obj@clust)

#' @describeIn componentsIntClust Accessor method to the \code{cutClusters}
#'   slot. Returns a vector with cluster membership for each candidate (format
#'   as \code{\link{cutree}}).
#' @export
setMethod("cutClusters", "componentsIntClust", function(obj) obj@cutClusters)

#' @describeIn componentsIntClust Returns a list with properties on how the
#'   clustering was performed.
#' @export
setMethod("clusterProperties", "componentsIntClust", function(obj) obj@properties)

#' @describeIn componentsIntClust Manually (re-)cut the dendrogram.
#' @param k,h Desired number of clusters or tree height to be used for cutting
#'   the dendrogram, respecitively. One or the other must be specified.
#'   Analogous to \code{\link{cutree}}.
#' @export
setMethod("treeCut", "componentsIntClust", function(obj, k = NULL, h = NULL)
{
    if (is.null(k) && is.null(h))
        stop("Either k or h should be specified")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertCount(k, positive = TRUE, null.ok = TRUE, add = ac)
    checkmate::assertNumber(h, lower = 0, finite = TRUE, null.ok = TRUE, add = ac)
    checkmate::reportAssertions(ac)
    
    obj@cutClusters <- cutree(obj@clust, k, h)
    
    obj@components <- genIntComponents(obj@cutClusters, obj@gInfo)
    obj@componentInfo <- genIntComponentInfo(obj@cutClusters)
    
    return(obj)
})

#' @describeIn componentsIntClust Automatically (re-)cut the dendrogram using
#'   the \code{\link{cutreeDynamicTree}} function from
#'   \pkg{\link{dynamicTreeCut}}.
#'
#' @template dynamictreecut
#'
#' @export
setMethod("treeCutDynamic", "componentsIntClust", function(obj, maxTreeHeight, deepSplit,
                                                           minModuleSize)
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assertNumber(maxTreeHeight, 0, finite = TRUE, add = ac)
    checkmate::assertFlag(deepSplit, add = ac)
    checkmate::assertCount(minModuleSize, positive = TRUE, add = ac)
    checkmate::reportAssertions(ac)
    
    obj@cutClusters <- doDynamicTreeCut(obj@clust, maxTreeHeight,
                                        deepSplit, minModuleSize)
    
    obj@components <- genIntComponents(obj@cutClusters, obj@gInfo)
    obj@componentInfo <- genIntComponentInfo(obj@cutClusters)
    
    return(obj)
})

#' @describeIn componentsIntClust draws a heatmap using the
#'   \code{\link{heatmap}} or \code{\link{d3heatmap}} function.
#' @param interactive If \code{TRUE} an interactive heatmap will be drawn (with
#'   \code{\link{d3heatmap}}).
#' @return \code{drawHeatMap} returns the same as \code{\link{heatmap}} or
#'   \code{\link{d3heatmap}}.
#' @aliases drawHeatMap
#' @export
setMethod("drawHeatMap", "componentsIntClust", function(obj, col, interactive, ...)
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assertCharacter(col, min.chars = 1, any.missing = FALSE, add = ac)
    checkmate::assertFlag(interactive, add = ac)
    checkmate::reportAssertions(ac)
    
    if (interactive)
        d3heatmap::d3heatmap(obj@clusterm, Colv = NA, distfun = function(d) dist(d, obj@properties$metric),
                             hclustfun = function(h) hclust(h, obj@properties$method),
                             scale = "none", colors = col, ...)
    else
        heatmap(obj@clusterm, Colv = NA, distfun = function(d) dist(d, obj@properties$metric),
                hclustfun = function(h) hclust(h, obj@properties$method),
                scale = "none", col = col, ...)
})

#' @describeIn componentsIntClust makes a plot for all (normalized) intensity
#'   profiles of the feature groups within a given cluster.
#' @param index Numeric component/cluster index.
#' @export
setMethod("plotInt", "componentsIntClust", function(obj, index, ...)
{
    checkmate::assertInt(index, lower = 1, upper = length(obj@cutClusters), null.ok = TRUE)
    
    plotm <- obj@clusterm[rownames(obj@clusterm) %in% rownames(obj@gInfo)[obj@cutClusters == index], , drop = FALSE]
    nsamp <- ncol(plotm)
    
    plot(x = c(0, nsamp), y = c(0, max(plotm)), type = "n", xlab = "", ylab = "normalized intensity", xaxt = "n", ...)
    axis(1, seq_len(nsamp), colnames(plotm), las = 2)
    
    px <- seq_len(nsamp)
    for (i in seq_len(nrow(plotm)))
        lines(x = px, y = plotm[i, ])
    
    invisible(NULL)
})

#' @describeIn componentsIntClust generates a dendrogram from a given cluster
#'   object and optionally highlights resulting branches when the cluster is
#'   cut.
#' @param pal Colour palette to be used from \pkg{\link{RColorBrewer}}.
#' @param numericLabels Set to \code{TRUE} to label with numeric indices instead
#'   of (long) feature group names.
#' @param \dots Any arguments directly given to \code{\link{plot.dendrogram}}.
#' @export
setMethod("plot", "componentsIntClust", function(x, pal = "Paired", numericLabels = TRUE, ...)
{
    checkmate::assertString(pal, min.chars = 1)
    dendro <- as.dendrogram(x@clust)
    if (numericLabels)
        dendextend::labels(dendro) <- seq_along(x@cutClusters)
    plotDendroWithClusters(dendro, x@cutClusters, pal, ...)
    invisible(NULL)
})

#' @describeIn componentsIntClust Plots the average silhouette width when the
#'   clusters are cut by a sequence of k numbers. The k value with the highest
#'   value (marked in the plot) may be considered as the optimal number of
#'   clusters.
#' @param kSeq An integer vector containing the sequence that should be used for
#'   average silhouette width calculation.
#' @export
#' @aliases plotSilhouettes
setMethod("plotSilhouettes", "componentsIntClust", function(obj, kSeq, ...)
{
    checkmate::assertIntegerish(kSeq, lower = 2, any.missing = FALSE)
    
    silInfo <- vector("list", length(kSeq))
    maxmw <- maxk <- NULL
    
    meanws <- sapply(kSeq, function(k)
    {
        sil <- silhouette(cutree(obj@clust, k = k), obj@distm)
        summary(sil)$avg.width
    })
    
    plot(x = kSeq, y = meanws, pch = 16, type = "b", xaxt = "none",
         xlab = "cluster k", ylab = "mean silhouette width", ...)
    axis(1, kSeq)
    abline(v = kSeq[which.max(meanws)], lty = 2)
    
    invisible(NULL)
})

#' @details \code{generateComponentsIntClust} generates components based on
#'   intensity profiles of feature groups. Hierarchical clustering is performed
#'   on normalized (and optionally replicate averaged) intensity data and the
#'   resulting dendrogram is automatically cut with
#'   \code{\link{cutreeDynamicTree}}. The distance matrix is calculated with
#'   \code{\link{daisy}} and clustering is performed with \code{\link{hclust}}.
#'   The clustering of the resulting components can be further visualized and
#'   modified using the methods defined for \code{\link{componentsIntClust}}.
#'
#' @param method Clustering method that should be applied (passed to
#'   \code{\link{hclust}}).
#' @param metric Distance metric used to calculate the distance matrix (passed
#'   to \code{\link{daisy}}).
#' @param normFunc Function that should be used for normalization of data.
#'   Intensitity values of a feature group will be divided by the result of this
#'   function when it is called with all intensity values of that feature group.
#'   For example, when \code{\link{max}} is used normalized intensities will be
#'   between zero and one.
#' @param average If \code{TRUE} then all intensitity data will be averaged for
#'   each replicate group.
#'
#' @template dynamictreecut
#'
#' @rdname component-generation
#' @export
generateComponentsIntClust <- function(fGroups, method = "complete", metric = "euclidean", 
                                       normFunc = max, average = TRUE,
                                       maxTreeHeight = 1, deepSplit = TRUE,
                                       minModuleSize = 1)
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    checkmate::assertFunction(normFunc, add = ac)
    checkmate::assertString(metric, add = ac)
    checkmate::assertString(method, add = ac)
    checkmate::assertFlag(average, add = ac)
    checkmate::reportAssertions(ac)
    
    if (length(fGroups) == 0)
        return(componentsIntClust(components = list(), componentInfo = data.table(), clusterm = matrix(),
                                  distm = structure(list(), class = "dissimilarity"),
                                  clust = structure(list(), class = "hclust"), cutClusters = numeric(),
                                  gInfo = data.frame(), properties = list(), algorithm = "IntClust"))
    
    if (average)
    {
        gTable <- averageGroups(fGroups)
        analysis <- unique(analysisInfo(fGroups)$group)
    }
    else
    {
        gTable <- groups(fGroups)
        analysis <- analysisInfo(fGroups)$analysis
    }
    
    if (length(analysis) < 2)
        stop(paste("Need at least >= 2", if (average) "replicate groups" else "analyses"))
    
    clusterdt <- copy(gTable)
    
    cat("Normalizing data... ")
    normv <- clusterdt[, lapply(.SD, normFunc)]
    for (g in seq_along(clusterdt))
        set(clusterdt, j = g, value = clusterdt[[g]] / normv[[g]])
    cat("Done!\n")
    
    clusterm <- as.matrix(transpose(clusterdt))
    rownames(clusterm) <- colnames(gTable)
    colnames(clusterm) <- analysis
    
    cat("Calculating distance matrix... ")
    distm <- daisy(clusterm, metric)
    cat("Done!\n")
    
    cat("Hierarchical clustering... ")
    clust <- hclust(distm, method)
    cat("Done!\n")
    
    cutClusters <- doDynamicTreeCut(clust, maxTreeHeight, deepSplit, minModuleSize)
    
    gInfo <- groupInfo(fGroups)
    comps <- genIntComponents(cutClusters, gInfo)
    cInfo <- genIntComponentInfo(cutClusters)
    
    return(componentsIntClust(components = comps, componentInfo = cInfo, clusterm = clusterm, distm = distm,
                              clust = clust, cutClusters = cutClusters, gInfo = gInfo,
                              properties = list(metric = metric, method = method, average = average),
                              algorithm = "IntClust"))
}
