# SPDX-FileCopyrightText: 2016-2026 Rick Helmus <r.helmus@uva.nl>
#
# SPDX-License-Identifier: GPL-3.0-only

#' @include main.R
#' @include compounds.R
#' @include utils-sirius.R
#' @include feature_groups-set.R
NULL

#' Compounds class for SIRIUS results.
#'
#' This class is derived from \code{\link{compounds}} and contains additional specific \command{SIRIUS} data.
#'
#' Objects from this class are generated by \code{\link{generateCompoundsSIRIUS}}
#'
#' @slot fingerprints A \code{list} with for each feature group result a \code{data.table} containing fingerprints
#'   obtained with \command{CSI:FingerID}.
#'
#' @templateVar class compoundsSIRIUS
#' @template class-hierarchy
#'
#' @seealso \code{\link{compounds}} and \code{\link{generateCompoundsSIRIUS}}
#'
#' @inherit generateCompoundsSIRIUS references
#'
#' @export
compoundsSIRIUS <- setClass("compoundsSIRIUS", slots = c(fingerprints = "list"),
                            contains = "compounds")

processSIRIUSCompounds <- function(msFName, outPath, MSMS, database, adduct, topMost)
{
    resultPath <- getSiriusResultPath(outPath, msFName)
    results <- scRanges <- fingerprints <- data.table()
    
    if (length(resultPath) != 0) # zero for no results
    {
        summary <- file.path(resultPath, "structure_candidates.tsv")
        summaryForms <- file.path(resultPath, "formula_candidates.tsv")
        if (file.exists(summary) && file.exists(summaryForms))
        {
            results <- fread(summary)
            results <- unifySirNames(results)
            resultsForm <- fread(summaryForms)
            
            # NOTE: so far SIRIUS only has one score
            if (nrow(results) > 0)
                scRanges <- list(score = range(results$score))
            
            # manually sort results: SIRIUS seems to sometimes randomly order results with equal scores
            # NOTE: do this before topMost filter step below to ensure proper filtering
            setorderv(results, c("score", "identifier"), order = c(-1, 1))
            
            if (!is.null(topMost))
            {
                if (nrow(results) > topMost)
                    results <- results[seq_len(topMost)] # results should already be sorted on score
            }
            
            # identifiers to characters, as they sometimes are and sometimes aren't depending on if multiple are present
            results[, identifier := as.character(identifier)]
            
            # NOTE: fragment info is based on SIRIUS results, ie from formula
            # prediction and not by compounds! Hence, results are the same for
            # candidates with the same formula.
            fragFiles <- patRoon:::getAndPrepareSIRIUSResFiles(resultPath, "spectra", "tsv")
            for (ff in fragFiles)
            {
                fragInfo <- fread(ff)
                fragInfo[, ionization := gsub(" ", "", ionization)]
                fragInfo[, PLID := sapply(mz, function(omz) MSMS[which.min(abs(omz - mz))]$ID)]
                
                # it is quite a journey to see find the relevant fragment files, especially with non-standard adducts...
                # 1. figure out, from the file name, to which formula candidate it belongs to
                # 2. but, the formula that is part of the file name is some strange half-neutralized form
                # 3. so dig in the formula summary file to which ionized formula this should belong to by looking at the 'precursorFormula' column
                fragFileFormName <- getFormulaFromSIRIUSResFile(ff, "tsv")
                fragFileFormNameNeutral <- resultsForm[match(fragFileFormName, precursorFormula)]$molecularFormula

                wh <- which(results$neutral_formula %in% fragFileFormNameNeutral)
                
                # Remove zero intensity peaks that aren't actually present in the peak list. These seem to be precursor
                # peaks, taking into account the various adduct forms of SIRIUS...
                fragInfo <- fragInfo[intensity != 0]
                
                fragInfo[, c("rel.intensity", "exactmass", "intensity") := NULL]
                
                if (length(wh) > 0)
                {
                    # sirius neutralizes fragments, make them ion again
                    if (!is.null(fragInfo[["implicitAdduct"]]))
                        ionImpAdducts <- ifelse(nzchar(fragInfo$implicitAdduct),
                                                mapply(paste0("+", fragInfo$implicitAdduct, "]"), fragInfo$ionization,
                                                       FUN = sub, MoreArgs = list(pattern = "\\]")),
                                                fragInfo$ionization)
                    else
                        ionImpAdducts <- fragInfo$ionization
                    setnames(fragInfo, "formula", "formula_SIR")
                    fragInfo[, ion_formula := mapply(formula_SIR, ionImpAdducts, FUN = calculateIonFormula)]
                    
                    ionform <- calculateIonFormula(results$neutral_formula[wh[1]], adduct)
                    fragInfo[, neutral_loss := sapply(ion_formula, subtractFormula, formula1 = ionform)]
                    
                    set(results, wh, "fragInfo", list(list(fragInfo)))
                    set(results, wh, "explainedPeaks", nrow(fragInfo))
                }
            }
            
            if (is.null(results[["fragInfo"]]))
            {
                # warning(sprintf("no fragment info for %s", cmd$gName))
                results[, fragInfo := list(rep(list(data.table(mz = numeric(0), ion_formula = character(0),
                                                               neutral_loss = character(0),  score = numeric(0),
                                                               PLID = numeric(0))),
                                               nrow(results)))]
                results[, explainedPeaks := 0]
            }
            results[, database := database][]
        }
        
        if (nrow(results) > 0)
            fingerprints <- loadSIRIUSFingerprints(resultPath, results$neutral_formula, adduct)
    }
    
    ret <- list(comptab = results, scRanges = scRanges, fingerprints = fingerprints)
    return(ret)
}


#' @rdname compounds-class
#' @export
setMethod("delete", "compoundsSIRIUS", function(obj, i = NULL, j = NULL, ...)
{
    obj <- callNextMethod()
    return(syncSIRFPs(obj))
})

#' @rdname pred-quant
#' @export
setMethod("predictRespFactors", "compoundsSIRIUS", function(obj, fGroups, calibrants, eluent, organicModifier, pHAq,
                                                            concUnit = "ugL", calibConcUnit = concUnit, type = "FP")
{
    checkPackage("MS2Quant", "kruvelab/MS2Quant")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    assertQuantEluent(eluent, fGroups, add = ac)
    checkmate::assertChoice(organicModifier, c("MeOH", "MeCN"), add = ac)
    checkmate::assertNumber(pHAq, finite = TRUE, add = ac)
    aapply(assertConcUnit, . ~ concUnit + calibConcUnit, fixed = list(add = ac))
    checkmate::assertChoice(type, c("FP", "SMILES", "both"), add = ac)
    checkmate::reportAssertions(ac)
    
    if (type == "SMILES" || type == "both")
        obj <- callNextMethod(obj, fGroups = fGroups, calibrants = calibrants, eluent = eluent,
                              organicModifier = organicModifier, pHAq = pHAq, concUnit = concUnit,
                              calibConcUnit = calibConcUnit, updateScore = FALSE, scoreWeight = 1)

    calibrants <- assertAndPrepareQuantCalib(calibrants, calibConcUnit)
    
    if (length(obj) == 0)
        return(obj)
    
    if (type == "FP" || type == "both")
    {
        printf("Predicting response factors from fingerprints with MS2Quant for %d candidates...\n", length(obj))
        res <- predictRespFactorsSIRFPs(obj, groupInfo(fGroups), calibrants, eluent, organicModifier, pHAq, concUnit)
        obj@MS2QuantMeta <- res$MD
        
        obj@groupAnnotations <- Map(groupNames(obj), annotations(obj), f = function(grp, ann)
        {
            ann <- copy(ann)
            if (nrow(res$RFs) == 0)
            {
                ann[, RF_SIRFP := NA_real_]
                return(ann)
            }
        
            if (!is.null(ann[["RF_SIRFP"]]))
                ann[, RF_SIRFP := NULL] # clearout for merge below    
            return(merge(ann, res$RFs[group == grp, c("neutral_formula", "RF_SIRFP"), with = FALSE],
                         by = "neutral_formula", sort = FALSE, all.x = TRUE))
        })
        
        obj <- addCompoundScore(obj, "RF_SIRFP", FALSE, 1)
    }
    
    return(obj)
})

#' @rdname pred-tox
#' @export
setMethod("predictTox", "compoundsSIRIUS", function(obj, type = "FP", LC50Mode = "static", concUnit = "ugL")
{
    checkPackage("MS2Tox", "kruvelab/MS2Tox")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertChoice(type, c("FP", "SMILES", "both"), add = ac)
    checkmate::assertChoice(LC50Mode, c("static", "flow"), add = ac)
    assertConcUnit(concUnit, add = ac)
    checkmate::reportAssertions(ac)
    
    if (type == "SMILES" || type == "both")
        obj <- callNextMethod(obj, LC50Mode = LC50Mode, concUnit = concUnit, updateScore = FALSE, scoreWeight = 1)
    
    if (length(obj) == 0)
        return(obj)
    
    if (type == "FP" || type == "both")
    {
        printf("Predicting LC50 values from fingerprints with MS2Tox for %d candidates...\n", length(obj))
        LC50Tab <- predictLC50SIRFPs(obj, LC50Mode, concUnit = concUnit)
        
        obj@groupAnnotations <- Map(groupNames(obj), annotations(obj), f = function(grp, ann)
        {
            ann <- copy(ann)
            if (nrow(LC50Tab) == 0)
            {
                ann[, LC50_SIRFP := NA_real_]
                return(ann)
            }

            if (!is.null(ann[["LC50_SIRFP"]]))
                ann[, LC50_SIRFP := NULL] # clearout for merge below    
            return(merge(ann, LC50Tab[group == grp, c("neutral_formula", "LC50_SIRFP"), with = FALSE],
                         by = "neutral_formula", sort = FALSE, all.x = TRUE))
        })
        
        obj <- addCompoundScore(obj, "LC50_SIRFP", FALSE, 1)
    }
    
    return(obj)
})


#' Compound annotation with SIRIUS
#'
#' Uses \href{https://bio.informatik.uni-jena.de/software/sirius/}{SIRIUS} in combination with
#' \href{https://www.csi-fingerid.uni-jena.de/}{CSI:FingerID} for compound annotation.
#'
#' @templateVar algo SIRIUS
#' @templateVar do generate compound candidates
#' @templateVar generic generateCompounds
#' @templateVar algoParam sirius
#' @template algo_generator
#'
#' @details Similar to \code{\link{generateFormulasSIRIUS}}, candidate formulae are generated with SIRIUS. These results
#'   are then fed to CSI:FingerID to acquire candidate structures. Candidate formulae without any assigned structure
#'   will be removed (unlike \code{\link{generateFormulasSIRIUS}}). This method requires the availability of MS/MS data,
#'   and feature groups without it will be ignored.
#'
#' @param fingerIDDatabase Database specifically used for \command{CSI:FingerID}. If \code{NULL}, the value of the
#'   \code{formulaDatabase} parameter will be used or \code{"pubchem"} when that is also \code{NULL}. Sets the
#'   \option{--fingerid-db} option.
#' @param topMostFormulas Do not return more than this number of candidate formulae. Note that only compounds for these
#'   formulae will be searched. Sets the \option{--candidates} commandline option.
#' @param verbose If \code{TRUE} then more output is shown in the terminal.
#'
#' @templateVar ident TRUE
#' @template sirius-args
#' @template sirius_form-args
#' @template adduct-arg
#' @template comp_algo-args
#' @template specSimParams_annSim-arg
#' @template minIMSSpecSim-arg
#'
#' @inheritParams generateCompounds
#'
#' @return A \code{\link{compoundsSIRIUS}} object.
#'
#' @templateVar what \code{generateCompoundsSIRIUS}
#' @template uses-multiProc
#'
#' @templateVar what generateCompoundsSIRIUS
#' @template main-rd-method
#' @export
setMethod("generateCompoundsSIRIUS", "featureGroups", function(fGroups, MSPeakLists,
                                                               specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                                               relMzDev = defaultLim("mz", "narrow_rel"), adduct = NULL,
                                                               projectPath = NULL, elements = "CHNOP",
                                                               profile = "qtof", formulaDatabase = NULL,
                                                               fingerIDDatabase = "pubchem", noise = NULL,
                                                               cores = NULL, topMost = 100, topMostFormulas = 5,
                                                               login = "check", alwaysLogin = FALSE,
                                                               extraOptsGeneral = NULL,
                                                               extraOptsFormula = NULL, minIMSSpecSim = 0,
                                                               verbose = TRUE, splitBatches = FALSE, dryRun = FALSE)
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    checkmate::assertClass(MSPeakLists, "MSPeakLists", add = ac)
    assertSpecSimParams(specSimParams, add = ac)
    checkmate::assertNumber(relMzDev, lower = 0, finite = TRUE, add = ac)
    checkmate::assertString(projectPath, null.ok = TRUE, add = ac)
    aapply(checkmate::assertString, . ~ elements + profile + fingerIDDatabase, fixed = list(add = ac))
    aapply(checkmate::assertString, . ~ formulaDatabase + fingerIDDatabase, null.ok = TRUE, fixed = list(add = ac))
    checkmate::assertNumber(noise, lower = 0, finite = TRUE, null.ok = TRUE, add = ac)
    checkmate::assertCount(cores, positive = TRUE, null.ok = TRUE, add = ac)
    aapply(checkmate::assertCount, . ~ topMost + topMostFormulas, positive = TRUE, fixed = list(add = ac))
    assertSIRIUSLogin(login, add = ac)
    checkmate::assertFlag(alwaysLogin, add = ac)
    aapply(checkmate::assertCharacter, . ~ extraOptsGeneral + extraOptsFormula, null.ok = TRUE, fixed = list(add = ac))
    checkmate::assertNumber(minIMSSpecSim, lower = 0, finite = TRUE, add = ac)
    checkmate::assertFlag(verbose, add = ac)
    checkmate::assertFlag(splitBatches, add = ac)
    checkmate::assertFlag(dryRun, add = ac)
    checkmate::reportAssertions(ac)

    if (length(fGroups) == 0)
        return(compoundsSIRIUS(algorithm = "sirius"))
    
    if (!is.null(projectPath))
        projectPath <- normalizePath(projectPath, mustWork = FALSE)
    
    adduct <- checkAndToAdduct(adduct, fGroups)
    if (is.null(fingerIDDatabase))
        fingerIDDatabase <- if (!is.null(formulaDatabase)) formulaDatabase else "pubchem"

    IMSSpecSims <- getIMSFeatAnnSpecSims(MSPeakLists, fGroups, minIMSSpecSim, specSimParams)
    
    gCount <- length(fGroups)
    printf("Processing %d feature groups with SIRIUS+CSI:FingerID...\n", gCount)
    
    results <- doSIRIUS(fGroups, MSPeakLists, FALSE, profile, adduct, relMzDev, elements,
                        formulaDatabase, noise, cores, "structure", fingerIDDatabase, topMostFormulas, projectPath,
                        login, alwaysLogin, extraOptsGeneral, extraOptsFormula, IMSSpecSims, NULL, verbose,
                        "compoundsSIRIUS", patRoon:::processSIRIUSCompounds, list(database = fingerIDDatabase,
                                                                                  topMost = topMost),
                        splitBatches, dryRun)
    
    # prune empty/NULL results
    if (length(results) > 0)
        results <- results[sapply(results, function(r) !is.null(r$comptab) && nrow(r$comptab) > 0, USE.NAMES = FALSE)]
    
    if (verbose)
    {
        printf("-------\n")
        ngrp <- length(results)
        printf("Assigned %d compounds to %d feature groups (%.2f%%).\n", sum(unlist(lapply(results, function(r) nrow(r$comptab)))),
               ngrp, if (gCount == 0) 0 else ngrp * 100 / gCount)
    }

    ret <- compoundsSIRIUS(groupAnnotations = lapply(results, "[[", "comptab"), scoreTypes = "score",
                           scoreRanges = lapply(results, "[[", "scRanges"),
                           fingerprints = pruneList(lapply(results, "[[", "fingerprints"), checkZeroRows = TRUE),
                           algorithm = "sirius", MSPeakLists = MSPeakLists, specSimParams = specSimParams,
                           IMSSpecSims = IMSSpecSims, gNames = names(fGroups))
    
    if (!is.null(IMSSpecSims))
    {
        mss <- IMSSpecSims[ims_precursor_group %chin% names(ret@fingerprints)]
        if (nrow(mss) > 0)
            ret@fingerprints[mss$group] <- copy(ret@fingerprints[mss$ims_precursor_group])
    }
    
    return(ret)
})

#' @template featAnnSets-gen_args
#' @rdname generateCompoundsSIRIUS
#' @export
setMethod("generateCompoundsSIRIUS", "featureGroupsSet", function(fGroups, MSPeakLists,
                                                                  specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                                                  relMzDev = defaultLim("mz", "narrow_rel"), adduct = NULL,
                                                                  projectPath = NULL, ..., setThreshold = 0,
                                                                  setThresholdAnn = 0, setAvgSpecificScores = FALSE)
{
    checkmate::assertCharacter(projectPath, len = length(sets(fGroups)), null.ok = TRUE)
    sa <- if (!is.null(projectPath)) lapply(projectPath, function(p) list(projectPath = p)) else list()
    generateCompoundsSet(fGroups, MSPeakLists, specSimParams, adduct, generateCompoundsSIRIUS, relMzDev = relMzDev, ...,
                         setThreshold = setThreshold, setThresholdAnn = setThresholdAnn,
                         setAvgSpecificScores = setAvgSpecificScores, setArgs = sa)
})

# UNDONE: docs, class name
#' @export
compoundsSIRIUS6 <- setClass("compoundsSIRIUS6", contains = "compounds")

doSIRIUS60Login <- function(login, force, SIRIUSAPI)
{
    if (isFALSE(login))
        return(invisible(NULL)) # no need to do anything
    
    isLoggedIn <- SIRIUSAPI$login_and_account_api$IsLoggedIn()
    
    if (length(login) == 1 && login == "check" && !isLoggedIn)
        stop("There is no active SIRIUS login. Please consult the SIRIUS documentation and patRoon handbook for details.")
    
    else if (force || !isLoggedIn)
    {
        if (length(login) == 1 && login == "interactive")
        {
            if (!interactive())
                stop("Cannot perform interactive login in non-interactive R sessions!", call. = FALSE)
            
            # NOTE: if "username" is part of the prompt then the RStudio backend of getPass won't hide the text input
            login <- c(username = getPass::getPass("Please enter your SIRIUS username", noblank = TRUE),
                       password = getPass::getPass("Please enter your SIRIUS password", noblank = TRUE))
        }
        
        if (!"username" %in% names(login) || !nzchar(login["username"]))
            stop("Please provide the username of your SIRIUS account", call. = FALSE)
        if (!"password" %in% names(login) || !nzchar(login["password"]))
            stop("Please provide the password of your SIRIUS account", call. = FALSE)
        
        SIRCreds <- RSirius::AccountCredentials$new(username = login["username"], password = login["password"])
        SIRIUSAPI$login_and_account_api$Login(accept_terms = TRUE, account_credentials = SIRCreds)
    }
    invisible(NULL)
}

startSIRIUS <- function(path)
{
    checkPackage("RSirius", "sirius-ms/sirius-client-openAPI", ghSubDir = "client-api_r/generated")
    
    sdk <- RSirius::SiriusSDK$new()
    # UNDONE: make this configurable?
    # UNDONE: somehow default to a new SIRIUS instance? May make more sense for unattended processing?
    # SIRIUSAPI <- sdk$attach_or_start_sirius()
    SIRIUSAPI <- sdk$attach_to_sirius()
    shutdownSIR <- FALSE
    if (is.null(SIRIUSAPI))
    {
        SIRIUSAPI <- sdk$start_sirius(sirius_path = path)
        shutdownSIR <- TRUE
    }
    withr::defer_parent({
        tryCatch({
            if (shutdownSIR)
                sdk$shutdown_sirius()
        }, error = function(e) NULL)
    })
    
    return(SIRIUSAPI)
}

# UNDONE
generateCompoundsSIRIUS60 <- function(fGroups, MSPeakLists, specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                      adduct = NULL, config = NULL, login = "check", alwaysLogin = FALSE,
                                      minIMSSpecSim = 0, projectPath = NULL, runMode = "execute", SIRIUSAPI = NULL,
                                      SIRIUSPath = NULL, verbose = TRUE)
{
    # UNDONE: error handling for SIRIUS API calls
    # UNDONE: add fingerprints
    # UNDONE: handle IMSSpecSims: test and add to hash
    # UNDONE: add database column --> once links are fixed and once configs are defined
    # UNDONE: replace SIRIUSPath by patRoonExt
    # UNDONE: caching
    # UNDONE: doc that login means accepting terms?
    # UNDONE: properly set adducts (are spaces needed?)
    # UNDONE: ensure/force that the right steps are enabled in config
    
    checkPackage("RSirius", "sirius-ms/sirius-client-openAPI", ghSubDir = "client-api_r/generated")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(MSPeakLists, "MSPeakLists", add = ac)
    assertSpecSimParams(specSimParams, add = ac)
    checkmate::assertR6(config, null.ok = TRUE, add = ac)
    assertSIRIUSLogin(login, add = ac)
    checkmate::assertFlag(alwaysLogin, add = ac)
    checkmate::assertNumber(minIMSSpecSim, lower = 0, finite = TRUE, add = ac)
    checkmate::assert(
        checkmate::checkPathForOutput(projectPath, overwrite = TRUE, extension = "sirius"),
        checkmate::checkNull(projectPath),
        .var.name = "projectPath", add = ac
    )
    checkmate::assertChoice(runMode, c("execute", "read"), add = ac)
    checkmate::assertClass(SIRIUSAPI, "rsirius_api", null.ok = TRUE, add = ac)
    checkmate::assertFlag(verbose, add = ac)
    checkmate::reportAssertions(ac)
    
    if (runMode == "read" && (is.null(projectPath) || !file.exists(projectPath)))
        stop("projectPath must be provided and exist when runMode is 'read'", call. = FALSE)
    
    if (length(fGroups) == 0)
        return(compoundsSIRIUS6(algorithm = "sirius6"))
    
    adduct <- checkAndToAdduct(adduct, fGroups)
    
    IMSSpecSims <- getIMSFeatAnnSpecSims(MSPeakLists, fGroups, minIMSSpecSim, specSimParams)
    
    if (verbose)
        printf("Processing %d feature groups with SIRIUS+CSI:FingerID...\n", length(fGroups))
    
    projectID <- if (!is.null(projectPath) && length(names(projectPath) > 0)) names(projectPath)[1] else "patRoonProjectID"

    if (is.null(SIRIUSAPI))
        SIRIUSAPI <- startSIRIUS(SIRIUSPath)
    
    doSIRIUS60Login(login, alwaysLogin, SIRIUSAPI)
    
    projectPath <- if (is.null(projectPath))
        tempfile("patRoonSIRIUS", fileext = ".sirius")
    else
        normalizePath(projectPath, mustWork = FALSE, winslash = "/")

    if (file.exists(projectPath) && runMode == "read")
        SIRIUSAPI$projects_api$OpenProject(projectID, projectPath)
    else
    {
        unlink(projectPath)
        SIRIUSAPI$projects_api$CreateProject(projectID, projectPath)
    }

    
    makeSIRSpec <- function(pl, lev, pmz)
    {
        peaks <- Map(pl$mz, pl$intensity, f = RSirius::SimplePeak$new)
        ret <- RSirius::BasicSpectrum$new(msLevel = lev, peaks = peaks)
        if (lev > 1)
            ret$precursorMz = pmz
        return(ret)
    }
    
    db <- openCacheDBScope()
    baseHash <- makeHash(specSimParams, adduct, config, minIMSSpecSim)
    
    doFGroup <- function(grp)
    {
        if (!is.null(IMSSpecSims) && fg %chin% IMSSpecSims$group)
            return(FALSE)
        if (is.null(MSPeakLists[[fg]][["MS"]]) || is.null(MSPeakLists[[fg]][["MSMS"]]) ||
            !any(MSPeakLists[[fg]][["MS"]]$precursor))
            return(FALSE)
        return(TRUE)
    }
    
    gNamesTBD <- names(fGroups)[sapply(names(fGroups), doFGroup)]
    fgAdd <- getFGroupAdducts(gNamesTBD, annotations(fGroups)[match(gNamesTBD, group)], adduct, "sirius")
    hashes <- sapply(gNamesTBD,
                     \(g) makeHash(baseHash, fgAdd[[g]], MSPeakLists[[g]][precursor == TRUE]$mz, MSPeakLists[[fg]]$MSMS))
    cachedData <- pruneList(setNames(loadCacheData("compoundsSIRIUS", hashes, dbArg = db, simplify = FALSE), gNamesTBD))
    gNamesTBD <- setdiff(gNamesTBD, names(cachedData))

    if (length(gNamesTBD) > 0)
    {
        if (runMode == "execute")
        {
            SIRFeatList <- sapply(gNamesTBD, function(fg)
            {
                plmz <- MSPeakLists[[fg]]$MS[precursor == TRUE]$mz
                RSirius::FeatureImport$new(externalFeatureId = fg, ionMass = plmz, detectedAdducts = list("[M+Na]+"),
                                           charge = 1L, mergedMs1 = makeSIRSpec(MSPeakLists[[fg]]$MS, 1L, plmz),
                                           ms2Spectra = list(makeSIRSpec(MSPeakLists[[fg]]$MSMS, 2L, plmz)))
            }, simplify = FALSE)
            
            SIRIUSAPI$features_api$AddAlignedFeatures(project_id = projectID, SIRFeatList)
            
            if (is.null(config))
                config <- getSIRIUSConfig(SIRIUSAPI = SIRIUSAPI, SIRIUSPath = SIRIUSPath, login = FALSE) # NOTE: should already be logged in
            config$spectraSearchParams$enabled <- FALSE
            config$formulaIdParams$enabled <- TRUE
            config$structureDbSearchParams$enabled <- TRUE
            config$canopusParams$enabled <- TRUE # fails if disabled...
            config$msNovelistParams$enabled <- FALSE
            
            printf("Running SIRIUS job...\n")
            job <- SIRIUSAPI$jobs_api$StartJob(projectID, config)
            
            # NOTE: maxProgress can change during the job execution, so we normalize the current progress to it at each update
            prog <- openProgBar(0, 1)
            repeat
            {
                Sys.sleep(1)
                jp <- SIRIUSAPI$jobs_api$GetJob(projectID, job$id)$progress
                if (jp$state %in% c("CANCELED", "FAILED", "DONE"))
                    break
                setTxtProgressBar(prog, jp$currentProgress / jp$maxProgress)
            }
            setTxtProgressBar(prog, 1)
            close(prog)
        }
        
        SIRFeatListImp <- SIRIUSAPI$features_api$GetAlignedFeatures(projectID)
        names(SIRFeatListImp) <- sapply(SIRFeatListImp, \(f) if (is.null(f$externalFeatureId)) NA_character_ else f$externalFeatureId)
        SIRFeatListImp <- SIRFeatListImp[intersect(names(fGroups), names(SIRFeatListImp))] # sync and only keep relevant
        
        if (length(SIRFeatListImp) == 0)
            return(compoundsSIRIUS6(algorithm = "sirius6"))
        
        compTabs <- sapply(SIRFeatListImp, function(fi)
        {
            # BUG: opt_fields doesn't seem to do anything
            structCands <- SIRIUSAPI$features_api$GetStructureCandidates(projectID, fi$alignedFeatureId,
                                                                         opt_fields = c("dbLinks", "libraryMatches"))
            if (length(structCands) == 0)
                return(NULL)
            tab <- rbindlist(lapply(structCands, \(sc) sc$toList()), fill = TRUE)
            setnames(tab, c("inchiKey", "smiles", "structureName", "xlogP", "molecularFormula", "csiScore"),
                     c("InChIKey1", "SMILES", "compoundName", "XlogP", "neutral_formula", "score"), skip_absent = TRUE)
            # UNDONE: add InChI and InChIKey?
            
            formIDs <- unique(tab$formulaId)
            formCands <- sapply(formIDs, \(fid) SIRIUSAPI$features_api$GetFormulaCandidate(projectID, fi$alignedFeatureId, fid),
                                simplify = FALSE)
            fragInfos <- sapply(formIDs, function(fid)
            {
                as <- SIRIUSAPI$features_api$GetFormulaAnnotatedSpectrum(projectID, fi$alignedFeatureId, fid)
                PLMS2 <- MSPeakLists[[fi$externalFeatureId]]$MSMS
                ionform <- calculateIonFormula(as$spectrumAnnotation$molecularFormula,
                                               gsub(" ", "", as$spectrumAnnotation$adduct))
                rbindlist(lapply(as$peaks, function(p)
                {
                    if (!p$peakAnnotation$isValid()) # no annotations
                        return(NULL)
                    anns <- data.table(mz = p$mz, ion_formula_mz = p$peakAnnotation$exactMass,
                                       formula_SIR = p$peakAnnotation$molecularFormula,
                                       adduct = gsub(" ", "", p$peakAnnotation$adduct),
                                       error_mz = p$peakAnnotation$massDeviationMz,
                                       error_ppm = p$peakAnnotation$massDeviationPpm)
                    # add MSPL ID
                    anns[, PLID := PLMS2[which.min(abs(p$mz - mz))]$ID]
                    
                    # SIRIUS neutralizes fragments, make them ion again
                    anns[, ion_formula := mapply(formula_SIR, adduct, FUN = calculateIonFormula)]
                    anns[, neutral_loss := sapply(ion_formula, subtractFormula, formula1 = ionform)]
                    return(anns)
                }))
            }, simplify = FALSE)
            
            set(tab, j = "fragInfo", value = fragInfos[tab$formulaId])
            set(tab, j = "explainedPeaks", value = sapply(tab$fragInfo, nrow))
            
            tab <- removeDTColumnsIfPresent(tab, "formulaId")
            return(tab)
        }, simplify = FALSE)
        compTabs <- pruneList(compTabs, checkZeroRows = TRUE)
    }
    
    
    
    scRanges <- sapply(compTabs, \(ct) list(score = range(ct$score)), simplify = FALSE)
    
    if (verbose)
    {
        ngrp <- length(compTabs)
        printf("Assigned %d compounds to %d feature groups (%.2f%%).\n", sum(sapply(compTabs, nrow)),
               ngrp, if (length(fGroups) == 0) 0 else ngrp * 100 / length(fGroups))
    }
    
    return(compoundsSIRIUS6(groupAnnotations = compTabs, scoreTypes = "score", scoreRanges = scRanges,
                           algorithm = "sirius6", MSPeakLists = MSPeakLists, specSimParams = specSimParams,
                           IMSSpecSims = IMSSpecSims, gNames = names(fGroups)))
}

#' @export
getSIRIUSConfig <- function(config = NULL, import = NULL, login = "check", alwaysLogin = FALSE, SIRIUSAPI = NULL,
                            SIRIUSPath = NULL)
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assert(
        checkmate::checkString(config, min.chars = 1),
        checkmate::checkList(config),
        checkmate::checkScalarNA(config),
        checkmate::checkNull(config),
        .var.name = "config", add = ac
    )
    if (!is.null(import))
        checkmate::assertFileExists(import, add = ac)
    assertSIRIUSLogin(login, add = ac)
    checkmate::assertFlag(alwaysLogin, add = ac)
    checkmate::assertClass(SIRIUSAPI, "rsirius_api", null.ok = TRUE, add = ac)
    checkmate::reportAssertions(ac)
    
    if (!is.null(config) && !is.null(import))
        stop("Only one of 'config' and 'import' can be provided.", call. = FALSE)
    
    if (is.null(SIRIUSAPI))
        SIRIUSAPI <- startSIRIUS(SIRIUSPath)
    
    doSIRIUS60Login(login, alwaysLogin, SIRIUSAPI)

    if (!is.null(config) && is.na(config))
        return(unlist(SIRIUSAPI$jobs_api$GetJobConfigNames()))

    if (!is.null(import))
    {
        config <- RSirius::JobSubmission$new()
        config$validateJSON(import)
        config$fromJSON(import)
    }
    else if (is.null(config))
        config <- SIRIUSAPI$jobs_api$GetDefaultJobConfig(include_config_map = FALSE)
    else if (is.character(config))
        config <- SIRIUSAPI$jobs_api$GetJobConfig(config)

    return(config)
}
