# SPDX-FileCopyrightText: 2016-2026 Rick Helmus <r.helmus@uva.nl>
#
# SPDX-License-Identifier: GPL-3.0-only

#' @include main.R
#' @include mspeaklists.R
#' @include formulas.R
#' @include utils-sirius.R
NULL

#' Formulas class for SIRIUS results.
#'
#' This class is derived from \code{\link{formulas}} and contains additional specific \command{SIRIUS} data.
#'
#' Objects from this class are generated by \code{\link{generateFormulasSIRIUS}}
#'
#' @slot fingerprints A \code{list} with for each feature group result a \code{data.table} containing fingerprints
#'   obtained with \command{CSI:FingerID}. Will be empty unless the \code{getFingerprints} argument to
#'   \code{\link{generateFormulasSIRIUS}} was set to \code{TRUE}.
#'   \strong{NOTE:} not yet implemented.
#' @slot MS2QuantMeta Metadata from \pkg{MS2Quant} filled in by \code{predictRespFactors}.
#'   \strong{NOTE:} not yet implemented.
#'
#' @templateVar class formulasSIRIUS
#' @template class-hierarchy
#'
#' @seealso \code{\link{formulas}} and \code{\link{generateFormulasSIRIUS}}
#'
#' @inherit generateFormulasSIRIUS references
#'
#' @export
formulasSIRIUS <- setClass("formulasSIRIUS", slots = c(fingerprints = "list", MS2QuantMeta = "list"),
                           contains = "formulas")

#' @rdname formulas-class
#' @export
setMethod("delete", "formulasSIRIUS", function(obj, i = NULL, j = NULL, ...)
{
    obj <- callNextMethod()
    return(syncSIRFPs(obj))
})

#' @rdname pred-quant
#' @export
setMethod("predictRespFactors", "formulasSIRIUS", function(obj, fGroups, calibrants, eluent, organicModifier, pHAq,
                                                           concUnit = "ugL", calibConcUnit = concUnit)
{
    stop("predictRespFactors() with SIRIUS fingerprints is not working, since MS2Quant is incompatible with SIRIUS 6.0",
         call. = FALSE)
    
    checkPackage("MS2Quant", "kruvelab/MS2Quant")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    assertQuantEluent(eluent, fGroups, add = ac)
    checkmate::assertChoice(organicModifier, c("MeOH", "MeCN"), add = ac)
    checkmate::assertNumber(pHAq, finite = TRUE, add = ac)
    aapply(assertConcUnit, . ~ concUnit + calibConcUnit, fixed = list(add = ac))
    checkmate::reportAssertions(ac)
    
    calibrants <- assertAndPrepareQuantCalib(calibrants, calibConcUnit)
    
    if (length(obj) == 0)
        return(obj)
    
    printf("Predicting response factors from fingerprints with MS2Quant for %d candidates...\n", length(obj))
    res <- predictRespFactorsSIRFPs(obj, groupInfo(fGroups), calibrants, eluent, organicModifier, pHAq, concUnit)
    obj@MS2QuantMeta <- res$MD
    
    obj@groupAnnotations <- Map(groupNames(obj), annotations(obj), f = function(grp, ann)
    {
        ann <- copy(ann)
        if (nrow(res$RFs) == 0)
        {
            ann[, RF_SIRFP := NA_real_]
            return(ann)
        }
     
        if (!is.null(ann[["RF_SIRFP"]]))
            ann[, RF_SIRFP := NULL] # clearout for merge below    
        return(merge(ann, res$RFs[group == grp, c("neutral_formula", "RF_SIRFP"), with = FALSE], by = "neutral_formula",
                     sort = FALSE, all.x = TRUE))
    })

    # UNDONE: do something equivalent for formula rankings?    
    # obj <- addCompoundScore(obj, "RF_SIRFP", FALSE, 1)
    
    return(obj)
})

#' @rdname pred-tox
#' @export
setMethod("predictTox", "formulasSIRIUS", function(obj, LC50Mode = "static", concUnit = "ugL")
{
    stop("predictTox() with SIRIUS fingerprints is not working, since MS2Tox is incompatible with SIRIUS 6.0",
         call. = FALSE)
    
    checkPackage("MS2Tox", "kruvelab/MS2Tox")
    
    checkmate::assertChoice(LC50Mode, c("static", "flow"))
    assertConcUnit(concUnit)

    if (length(obj) == 0)
        return(obj)
    
    printf("Predicting LC50 values from fingerprints with MS2Tox for %d candidates...\n", length(obj))
    LC50Tab <- predictLC50SIRFPs(obj, LC50Mode, concUnit)
    
    obj@groupAnnotations <- Map(groupNames(obj), annotations(obj), f = function(grp, ann)
    {
        ann <- copy(ann)
        if (nrow(LC50Tab) == 0)
        {
            ann[, LC50_SIRFP := NA_real_]
            return(ann)
        }

        if (!is.null(ann[["LC50_SIRFP"]]))
            ann[, LC50_SIRFP := NULL] # clearout for merge below    
        return(merge(ann, LC50Tab[group == grp, c("neutral_formula", "LC50_SIRFP"), with = FALSE],
                     by = "neutral_formula", sort = FALSE, all.x = TRUE))
    })
    
    # UNDONE: do something equivalent for formula rankings?
    # obj <- addCompoundScore(obj, "LC50_SIRFP", FALSE, 1)
    
    return(obj)
})


#' Generate formula with SIRIUS
#'
#' Uses \href{https://bio.informatik.uni-jena.de/software/sirius/}{SIRIUS} to generate chemical formulae candidates.
#'
#' @templateVar algo SIRIUS
#' @templateVar do generate formula candidates
#' @templateVar generic generateFormulas
#' @templateVar algoParam sirius
#' @template algo_generator
#'
#' @details Note that \command{SIRIUS} requires availability of MS/MS data.
#'
#' @param verbose If \code{TRUE} then more output is shown.
#'
#' @template sirius-args
#' @template adduct-arg
#' @templateVar algo sirius
#' @template form_algo-args
#' @template minIMSSpecSim-arg
#'
#' @inheritParams generateFormulas
#'
#' @return A \code{\link{formulasSIRIUS}} object.
#'
#' @templateVar what generateFormulasSIRIUS
#' @template main-rd-method
#' @export
setMethod("generateFormulasSIRIUS", "featureGroups", function(fGroups, MSPeakLists,
                                                              specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                                              adduct = NULL, config = NULL, login = "check",
                                                              alwaysLogin = FALSE, calculateFeatures = FALSE,
                                                              featThreshold = 0, featThresholdAnn = 0.75,
                                                              minIMSSpecSim = 0, projectPath = NULL,
                                                              runMode = "execute", SIRIUSAPI = NULL, SIRIUSPath = NULL,
                                                              verbose = TRUE)
{
    # UNDONE: see generateCompoundsSIRIUS()
    # UNDONE: re-add setFormulaPLID() and absAlignMzDev arg
    # UNDONE: optionally load fingerprints

    checkPackage("RSirius", "sirius-ms/sirius-client-openAPI", ghSubDir = "client-api_r/generated")
    
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(MSPeakLists, "MSPeakLists", add = ac)
    assertSpecSimParams(specSimParams, add = ac)
    checkmate::assertR6(config, null.ok = TRUE, add = ac)
    assertSIRIUSLogin(login, add = ac)
    checkmate::assertFlag(alwaysLogin, add = ac)
    checkmate::assertFlag(calculateFeatures, add = ac)
    aapply(checkmate::assertNumber, . ~ featThreshold + featThresholdAnn + minIMSSpecSim,
           lower = 0, upper = 1, finite = TRUE, fixed = list(add = ac))
    checkmate::assert(
        checkmate::checkPathForOutput(projectPath, overwrite = TRUE, extension = "sirius"),
        checkmate::checkNull(projectPath),
        .var.name = "projectPath", add = ac
    )
    checkmate::assertChoice(runMode, c("execute", "read"), add = ac)
    checkmate::assertClass(SIRIUSAPI, "rsirius_api", null.ok = TRUE, add = ac)
    checkmate::assertFlag(verbose, add = ac)
    checkmate::reportAssertions(ac)
    
    if (length(fGroups) == 0)
        return(formulasSIRIUS6(algorithm = "sirius6"))
    
    adduct <- checkAndToAdduct(adduct, fGroups)
    
    IMSSpecSims <- getIMSFeatAnnSpecSims(MSPeakLists, fGroups, minIMSSpecSim, specSimParams)
    
    if (verbose)
        printf("Processing %d feature groups with SIRIUS...\n", length(fGroups))
    
    SIRResults <- runSIRIUS(runMode, fGroups, MSPeakLists, IMSSpecSims, adduct, SIRIUSAPI, SIRIUSPath, projectPath,
                            config, login, alwaysLogin, formulasOnly = TRUE, calculateFeatures = calculateFeatures,
                            cacheName = "formulasSIRIUS")
    
    prepRes <- function(res)
    {
        tab <- res$formCands
        if (nrow(tab) == 0)
            return(NULL)
        tab <- removeDTColumnsIfPresent(tab, "formulaId")
        return(tab)
    }
    
    featForms <- list()
    if (calculateFeatures)
    {
        featForms <- pruneList(sapply(SIRResults, \(x) lapply(x, prepRes), simplify = FALSE))
        formTabs <- generateGroupFormulasByConsensus(featForms,
                                                     lapply(groupFeatIndex(fGroups), function(x) sum(x > 0)),
                                                     featThreshold, featThresholdAnn, names(fGroups))
    }
    else
        formTabs <- pruneList(sapply(SIRResults, prepRes, simplify = FALSE))
    
    scRanges <- sapply(formTabs, \(ct) list(score = range(ct$score)), simplify = FALSE)
    
    if (verbose)
    {
        ngrp <- length(formTabs)
        printf("Assigned %d formulas to %d feature groups (%.2f%%).\n", sum(sapply(formTabs, nrow)),
               ngrp, if (length(fGroups) == 0) 0 else ngrp * 100 / length(fGroups))
    }
    
    return(formulasSIRIUS(groupAnnotations = formTabs, featureFormulas = featForms, scoreTypes = "score",
                          scoreRanges = scRanges, algorithm = "sirius", MSPeakLists = MSPeakLists,
                          specSimParams = specSimParams, IMSSpecSims = IMSSpecSims, gNames = names(fGroups)))
})

#' @template featAnnSets-gen_args
#' @rdname generateFormulasSIRIUS
#' @export
setMethod("generateFormulasSIRIUS", "featureGroupsSet", function(fGroups, MSPeakLists,
                                                                 specSimParams = getDefSpecSimParams(removePrecursor = TRUE),
                                                                 adduct = NULL, config = NULL, login = "check",
                                                                 alwaysLogin = FALSE, calculateFeatures = FALSE,
                                                                 featThreshold = 0, featThresholdAnn = 0.75,
                                                                 minIMSSpecSim = 0, projectPath = NULL, ...,
                                                                 setThreshold = 0, setThresholdAnn = 0,
                                                                 setAvgSpecificScores = FALSE)
{
    checkmate::assertCharacter(projectPath, len = length(sets(fGroups)), null.ok = TRUE)
    sa <- if (!is.null(projectPath)) lapply(projectPath, function(p) list(projectPath = p)) else list()
    generateFormulasSet(fGroups, MSPeakLists, specSimParams, adduct, generateFormulasSIRIUS, config = config,
                        login = login, alwaysLogin = alwaysLogin, calculateFeatures = calculateFeatures,
                        featThreshold = featThreshold, featThresholdAnn = featThresholdAnn,
                        minIMSSpecSim = minIMSSpecSim,  ..., setThreshold = setThreshold,
                        setThresholdAnn = setThresholdAnn, setAvgSpecificScores = setAvgSpecificScores, setArgs = sa)
})
