#### Dependencies

#' @importFrom graphics plot axis barplot close.screen grconvertX grconvertY grid layout legend lines par plot.new points polygon rasterImage rect screen segments split.screen strwidth text title xinch yinch
#' @importFrom grDevices adjustcolor colorRampPalette dev.off pdf png
#' @importFrom stats cutree dist hclust heatmap lm median rect.hclust sd setNames
#' @importFrom VennDiagram draw.pairwise.venn draw.single.venn draw.triple.venn draw.quad.venn draw.quintuple.venn
#' @importFrom plotly plot_ly add_trace plotlyOutput renderPlotly ggplotly config
#' @importFrom mzR openMSfile peaks header close
#' @importFrom xcms phenoData phenoData<- filepaths filepaths<- xcmsRaw peaks peaks<- groups profinfo profinfo<- groupidx xcmsSet group retcor groupval groupnames rawEIC sampnames groupidx<- groups<-
#' @importFrom fst compress_fst decompress_fst
#' @importFrom processx process poll
#' @importFrom Rdpack reprompt
#' @importClassesFrom CAMERA xsAnnotate
#' @import data.table
#' @import withr
#' @import enviPick
#' @import DBI
#' @import RSQLite
#' @import utils
#' @import rhandsontable
#' @import RColorBrewer
#' @import shiny
#' @import miniUI
#' @import rstudioapi
#' @import cluster
#' @import metfRag
#' @import templates
#' @import circlize
#' @import ggplot2
NULL # need this for doc generation

# UNDONE: rstudioapi optional?

#' @include cache.R
NULL

#### Generics

#' @include generics.R
NULL

#### Document generation

#' Workflow solutions for mass-spectrometry based non-target analysis.
#'
#' patRoon combines several open-source and vendor software solutions to
#' provide a complete workflow for non-target analysis from high resolution
#' mass-spectrometry data.
#'
#' @section Package options:
#'
#'   The following package options (see \code{\link{options}}) can be set:
#'
#'   \itemize{
#'
#'   \item \code{patRoon.cache.mode}: A \code{character} setting the current
#'   caching mode: \code{"save"} and \code{"load"} will only save/load results
#'   to/from the cache, \code{"both"} (default) will do both and \code{"none"}
#'   to completely disable caching. This option can be changed anytime, which
#'   might be useful, for instance, to temporarily disable cached results before
#'   running a function.
#'
#'   \item \code{patRoon.cache.fileName}: a \code{character} specifying the
#'   name of the cache file (default is \file{cache.sqlite}).
#'
#'   \item \code{patRoon.maxProcAmount}: The maximum number of processes that
#'   should be initiated in parallel. A good starting point is the number of
#'   cores available. Default is set by \code{\link[parallel]{detectCores}}.
#'
#'   \item \code{patRoon.path.GenForm}: The path to the \command{GenForm}
#'   executable. If not set (the default) the internal \code{GenForm} binary is
#'   used. Only set if you want to override the executable.
#'
#'   \item \code{patRoon.path.metFragCL}: The complete file path to the metFrag
#'   CL \file{jar} file that \emph{must} be set when using
#'   \code{\link{generateCompoundsMetfrag}}. Example:
#'   \code{"C:/MetFrag2.4.2-CL.jar"}.
#'
#'   \item \code{patRoon.path.SIRIUS}: The directory in which SIRIUS is
#'   installed. Unless the binaries can be located via the \option{PATH}
#'   environment variable, this \emph{must} be set when using
#'   \code{\link{generateFormulasSirius}} or
#'   \code{\link{generateCompoundsSirius}}. Example:
#'   \code{"C:/sirius-win64-3.5.1"}.
#'
#'   \item \code{patRoon.path.OpenMS}: The path in which the \command{OpenMS}
#'   binaries are installed. Usually the location is added to the \option{PATH}
#'   environment variable when OpenMS is installed, in which case this option
#'   can be left empty.
#'
#'   \item \code{patRoon.path.pngquant}: The path of the \command{pngquant}
#'   binary that is used when optimizing \file{.png} plots generated by
#'   \code{\link{reportMD}} (with \code{optimizePng} set to \code{TRUE}). If the
#'   binary can be located through the \option{PATH} environment variable this
#'   option can remain empty. Note that some of the functionality of
#'   \code{reportMD} only locates the binary through the \option{PATH}
#'   environment variable, hence, it is recommended to set up \option{PATH}
#'   instead.
#'
#'   }
#'
"_PACKAGE"

#' Analysis information
#'
#' Required information for analyses that should be processed and utilities to
#' automatically generate this information.
#'
#' @details Several properties need to be known about analyses that should be
#'   processed during various workflow steps such as
#'   \link[=feature-finding]{finding features}, averaging intensities of feature
#'   groups and blank subtraction. This information should be made available
#'   with an 'analysis info' object, which is a \code{data.frame} containing the
#'   following columns:
#'
#' @template analysisInfo-list
#'
#' @details Most functionality requires the data files to be in either the
#'   \file{.mzXML} or \file{.mzML} format. Functionality that utilizes Bruker
#'   DataAnalysis (\emph{e.g.} \code{\link{findFeaturesBruker}}) may only work
#'   with data files in the proprietary \file{.d} format. Therefore, when tools
#'   with varying requirements are mixed (a common scenario), the data files
#'   also need to be present in the required formats. To deal with this
#'   situation the data files with varying formats should all be placed in the
#'   same path that was used to specify the location of the analysis.
#'
#'   Whether analysis data files are present in multiple formats or not, each
#'   analysis should only be entered \emph{once}. The \code{analysis} column is
#'   used as a basename to automatically find back the data file with the
#'   required format, hence, analysis names should be specified as the file name
#'   without its file extension.
#'
#'   The \code{group} column is \emph{mandatory} and needs to be filled in for
#'   each analysis. The \code{ref} column should also be present, however, these
#'   may contain empty character strings (\code{""}) for analyses where no blank
#'   subtraction should occur. The \code{conc} column is only required when
#'   using the \code{\link{regression}} method and optional for the
#'   \code{\link{screenTargets}} method.
#'
#' @name analysis-information
NULL


#' Finding features
#'
#' Functions and classes for collection of features.
#'
#' Several functions exist to collect features (\emph{i.e.} retention and MS
#' information that represent potential compounds) from a set of analyses. All
#' 'feature finders' return an object derived from the \code{\link{features}}
#' base class. The next step in a general workflow is to group and align these
#' features across analyses by \link[=feature-grouping]{feature groupers}. Note
#' that some feature finders have a plethora of options which sometimes may have
#' a large effect on the quality of results. Fine-tuning parameters is therefore
#' important, and the optimum is largely dependent upon applied analysis
#' methodology and instrumentation.
#'
#' @param analysisInfo \link[=analysis-information]{Analysis info table}.
#' @param ... further parameters passed to \code{\link[xcms]{xcmsSet}}
#'   (\code{findFeaturesXCMS}), \code{\link[enviPick]{enviPickwrap}}
#'   (\code{featurefinderEnviPick}) or to selected feature finding algorithms
#'   (\code{findFeatures}).
#'
#' @name feature-finding
#' @return An object of a class which is derived from \code{\link{features}}.
#' @seealso \code{\link{features-class}} and \code{\link{analysis-information}}
NULL

#' Grouping of features
#'
#' Functions and classes for grouping of features across analyses.
#'
#' After \link[=feature-finding]{features have been found} the logical next step
#' is to align and group them across analyses. This process is necessary to
#' allow comparison of features between multiple analyses, which otherwise would
#' be difficult due to small deviations in retention and mass data. Thus,
#' algorithms of 'feature groupers' are used to collect features with similar
#' retention and mass data. In addition, advanced retention time alignment
#' algorithms exist to enhance grouping of features even with relative large
#' retention time deviations (\emph{e.g.} possibly observed from analyses
#' collected over a long period). Like \link[=feature-finding]{finding of
#' features}, various algorithms are supported which may have many parameters
#' that can be fine-tuned. This fine-tuning is likely to be necessary, since
#' optimal settings often depend on applied methodology and instrumentation.
#'
#' @param feat The \code{\link{features}} to be grouped.
#'   \code{importFeatureGroupsBrukerPA} and \code{importFeatureGroupsEnviMass}
#'   only support features generated by \code{\link{findFeaturesBruker}} and
#'   \code{\link{importFeaturesEnviMass}}, respectively.
#' @param rtalign Enable retention time alignment.
#' @param \dots Any parameters to be passed to the selected grouping/importing
#'   algorithm.
#'
#' @name feature-grouping
#' @return An object of a class which is derived from
#'   \code{\link{featureGroups}}.
#' @seealso \code{\link{featureGroups-class}}
NULL

#' Generation of MS Peak Lists
#'
#' Functionality to generate MS peak lists.
#'
#' Formula calculation and identification tools rely on mass spectra that belong
#' to features of interest. For processing, MS (and MS/MS) spectra are typically
#' reduced to a table with a column containing measured \emph{m/z} values and a
#' column containing their intensities. These 'MS peak lists' can then be used
#' for \link[=formula-generation]{formula generation} and
#' \link[=compound-generation]{compound generation}. By default, peak lists are
#' generated from all analyses containing a particular feature group. The main
#' advantage is that this will allow subsequent processes (at the moment only
#' formulae calculation) to generate a consensus from feature group data
#' originating from multiple analyses. Nevertheless, it might be useful to limit
#' to maximum amount of analyses (\code{topMost} parameter) to signficantly
#' reduce the processing time required for MS peak list extraction.
#'
#' Several functions exist to automatically extract MS peak lists for feature
#' groups.
#'
#' @param fGroups The \code{\link{featureGroups}} object from which MS peak
#'   lists should be extracted.
#' @param topMost Only extract MS peak lists from a maximum of \code{topMost}
#'   analyses with highest intensity. If \code{NULL} all analyses will be used.
#' @param maxRtMSWidth Maximum total chromatographic peak width (seconds) used
#'   for spectrum averaging. If \code{NULL} all spectra from a feature will be
#'   taken into account. Lower to decrease processing time.
#' @return A \code{\link{MSPeakLists}} object that can be used for formulae
#'   calculation and compound identification.
#' @seealso \code{\link{MSPeakLists-class}}
#' @name MSPeakLists-generation
NULL

#' Automatic chemical formula generation
#'
#' Functionality to automatically calculate chemical formulae from feature
#' groups and generate a consensus over all analyses.
#'
#' Several algorithms are provided to automatically generate formulae for given
#' feature groups. All tools use the accurate mass of a feature to
#' back-calculate candidate formulae. Depending on the algorithm and data
#' availability, other data such as isotopic pattern and MS/MS fragments may be
#' used to further improve formula assignment.
#'
#' @param fGroups \code{\link{featureGroups}} object for which formulae should
#'   be generated. This should be the same or a subset of the object that was
#'   used to create the specified \code{MSPeakLists} (only relevant for
#'   algorithms using \code{MSPeakLists}). In the case of a subset only the
#'   remaining feature groups in the subset are considered.
#' @param MSPeakLists An \code{\link{MSPeakLists}} object that was generated for
#'   the supplied \code{fGroups}.
#' @param adduct Sets the adduct form of measured ions. For
#'   \code{generateFormulasGenForm} the format is without brackets and charges
#'   (based on
#'   \href{http://fiehnlab.ucdavis.edu/staff/kind/Metabolomics/MS-Adduct-Calculator}{this
#'    website}), examples: \code{"M+H"}, \code{"M-H"}, \code{"M+Na"},
#'   \code{"M-e"}. For \code{generateFormulasSirius} the format is with brackets
#'   and charge, for example: \code{"[M+H]+"}, \code{"[M-H]-"},
#'   \code{"[M+Na]+"}, \code{"[M]+"}. Sets the \option{ion} and \option{--ion}
#'   commandline options for \command{GenForm} and \command{SIRIUS},
#'   respectively.
#' @param MSMode Whether formulae should be generated only from MS data
#'   (\code{"ms"}), MS/MS data (\code{"msms"}) or both (\code{"both"}). Using
#'   the latter option, unique formulae from MS data will still be reported if
#'   not predicted from MS/MS data. Formulae calculated from MS data that were
#'   also generated from MS/MS data will be removed.
#'
#' @templateVar genForm TRUE
#' @template form-args
#'
#' @template multiProc-args
#'
#' @return A \code{\link{formulas}} object containing all generated formulae.
#'
#' @seealso \code{\link{formulas-class}} and
#'   \code{\link{formulaConsensus-class}}. The
#'   \href{https://www.researchgate.net/publication/307964728_MOLGEN-MSMS_Software_User_Manual}{GenForm
#'   manual} (formerly known as MOLGEN-MSMS).
#' @name formula-generation
NULL

#' Automatic compound identification
#'
#' Functionality to automatically identify chemical compounds from feature
#' groups.
#'
#' Several algorithms are provided to automatically identify compounds for given
#' feature groups. To this end, each measured masses for all feature groups are
#' searched within online database(s) (\emph{e.g.}
#' \href{https://pubchem.ncbi.nlm.nih.gov/}{PubChem}) to retrieve a list of
#' potential candidate chemical compounds. Depending on the algorithm and its
#' parameters, further scoring of candidates is then performed using, for
#' instance, matching of measured and theoretical isotopic patterns, presence
#' within other data sources such as patent databases and similarity of measured
#' and in-silico predicted MS/MS fragments. Note that this process is often
#' quite time consuming, especially for large feature group sets. Therefore,
#' this is often one of the last steps within the workflow and not performed
#' before feature groups have been prioritized.
#'
#' @param fGroups \code{\link{featureGroups}} object for which compounds should
#'   be identified. This should be the same or a subset of the object that was
#'   used to create the specified \code{MSPeakLists}. In the case of a subset
#'   only the remaining feature groups in the subset are considered.
#' @param MSPeakLists A \code{\link{MSPeakLists}} object that was generated for
#'   the supplied \code{fGroups}.
#' @param adduct The assumed MS adduct. For \code{generateCompoundsMetfrag}: a
#'   numeric value (\emph{e.g.} \samp{1} for [M+H]+, \samp{-1} for [M-H]- and
#'   \samp{0} for [M]+/-, see the
#'   \href{http://c-ruttkies.github.io/MetFrag/projects/metfragcl/}{MetFrag CL}
#'   homepage for more). Please note that \code{isPositive} also needs to be
#'   set. For \code{generateCompoundsSirius}, a character string such as
#'   \code{"[M+H]+"}, \code{"[M-H]-"}, \code{"[M+Na]+"} and \code{"[M]+"}. Sets
#'   the \option{PrecursorIonMode} and \option{--ion} options, respectively.
#' @param topMost Only keep this number of candidates (per feature group) with
#'   highest score. Set to \code{NULL} to always keep all candidates, however,
#'   please note that this may result in significant usage of CPU/RAM resources
#'   for large numbers of candidates.
#'
#' @template multiProc-args
#'
#' @return A \code{\link{compounds}} object containing all tentatively
#'   identified compounds.
#'
#' @note At this point only mass spectrometric data from the most intense
#'   feature is used for compound identification.
#'
#' @seealso \code{\link{compounds-class}}
#' @name compound-generation
NULL

#' Grouping feature groups in components
#'
#' Functionality to automatically group related feature groups (\emph{e.g.}
#' isotopes, adducts and homologues) to assist and simplify compound annotation.
#'
#' Several algorithms are provided to group feature groups that are related in
#' some (chemical) way to each other. These components generally include
#' adducts, isotopes, in-source fragments and homologues. The linking of this
#' data is generally useful to provide more information for compound annotation
#' and reduce the data size and thus complexity.
#'
#' @param fGroups \code{\link{featureGroups}} object for which components should
#'   be generated.
#' @param ionization Which ionization polarity was used to generate the data:
#'   should be \code{"positive"} or \code{"negative"}.
#' @param extraOpts Named character vector with extra arguments directly passed
#'   to \code{\link{homol.search}} (\code{generateComponentsNontarget}) or
#'   \code{\link[CAMERA:annotate-methods]{CAMERA::annotate}}
#'   (\code{generateComponentsCAMERA}). Set to \code{NULL} to ignore.
#'
#' @return A \code{\link{components}} object containing all generated
#'   components.
#'
#' @name component-generation
NULL

#' Bruker DataAnalysis utilities
#'
#' Miscellaneous utility functions which interface with Bruker DataAnalysis
#'
#' These functions communicate directly with Bruker DataAnalysis to provide
#' various functionality, such as calibrating and exporting data and adding
#' chromatographic traces. For this the \pkg{RDCOMClient} package is
#' required to be installed.
#'
#' @param anaInfo \link[=analysis-information]{Analysis info table}
#'
#' @name bruker-utils
#'
#' @seealso \code{\link{analysis-information}}
NULL

#' Interactive GUI utilities
#'
#' Interactive utilities using \pkg{\link{shiny}} to provide a graphical user
#' interface (GUI).
#'
#' @param fGroups A \code{\link{featureGroups}} object.
#'
#' @name GUI-utils
NULL

