#' @include main.R
#' @include mspeaklists.R
#' @include utils-bruker.R
NULL

#' @details \code{generateDAMSPeakLists} uses Bruker DataAnalysis to generate MS
#'   peak lists. Naturally, this only works with analyses in the Bruker data
#'   format (\file{.d}). This function leverages DataAnalysis functionality to
#'   support averaging of spectra, background subtraction and identification of
#'   isotopes. In order to obtain mass spectra TICs will be added of the MS and
#'   relevant MS/MS signals.
#'
#' @param bgsubtr If \code{TRUE} background will be subtracted using the
#'   'spectral' algorithm.
#' @param clear Remove any existing chromatogram traces/mass spectra prior to
#'   making new ones.
#' @param save Save data files after completion.
#' @param MSMSType The type of MS/MS experiment performed: \code{"MSMS"} for
#'   MRM/AutoMSMS or \code{"BBCID"} for broadband CID.
#'
#' @note \code{generateDAMSPeakLists} requires that the \option{Component}
#'   column is active (Method-->Parameters-->Layouts-->Mass List Layout).
#'
#' @rdname MSPeakLists-generation
#' @export
generateDAMSPeakLists <- function(fGroups, bgsubtr = TRUE, maxRtMSWidth = 20, clear = TRUE, save = TRUE, MSMSType = "MSMS",
                                  avgFGroupParams = getDefAvgPListParams())
{
    # UNDONE: implement topMost

    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    aapply(checkmate::assertFlag, . ~ bgsubtr + clear + save, fixed = list(add = ac))
    checkmate::assertNumber(maxRtMSWidth, lower = 0, finite = TRUE, null.ok = TRUE, add = ac)
    checkmate::assertChoice(MSMSType, c("MSMS", "BBCID"), add = ac)
    assertAvgPListParams(avgFGroupParams, add = ac)
    checkmate::reportAssertions(ac)
    
    compounds <- generateDACompounds(fGroups, bgsubtr, maxRtMSWidth, clear, save, MSMSType)

    cacheDB <- openCacheDBScope()

    ftindex <- groupFeatIndex(fGroups)
    fTable <- featureTable(fGroups)
    anaInfo <- analysisInfo(fGroups)
    DA <- getDAApplication()

    hideDAInScope()

    # structure: [[analysis]][[fGroup]][[MSType]][[MSPeak]]
    ret <- list()

    for (anai in seq_along(compounds))
    {
        ana <- anaInfo$analysis[anai]
        findDA <- getDAFileIndex(DA, ana, anaInfo$path[anai])
        anac <- compounds[[anai]]
        gcount <- nrow(anac)

        setHash <- makeHash(compounds[anai], ana)
        cachedSet <- loadCacheSet("MSPeakListsDA", setHash, cacheDB)
        resultHashes <- vector("character", gcount)

        if (is.null(cachedSet))
        {
            cat("Deconvoluting spectra ...")
            DA[["Analyses"]][[findDA]][["Spectra"]]$Deconvolute()
            cat("Done!\n")
        }

        printf("Loading all MS peak lists for %d feature groups in analysis '%s'...\n", gcount, ana)
        prog <- txtProgressBar(0, gcount, style=3)

        for (grpi in seq_len(gcount))
        {
            gname <- colnames(ftindex)[grpi]

            specindMS <- anac[["MSSpec"]][grpi]
            if (specindMS == 0)
                next # no MS spectrum for this group/analysis, don't bother

            hash <- makeHash(setHash, gname)
            resultHashes[grpi] <- hash

            results <- NULL
            if (!is.null(cachedSet))
                results <- cachedSet[[hash]]
            if (is.null(results))
                results <- loadCacheData("MSPeakListsDA", hash, cacheDB)

            if (is.null(results))
            {
                results <- list()

                results$MS <- getDAPeakList(findDA, specindMS, FALSE, FALSE)

                specindMSMS <- anac[["MSMSSpec"]][grpi]
                if (specindMSMS != 0)
                    results$MSMS <- getDAPeakList(findDA, specindMSMS, FALSE, TRUE)

                saveCacheData("MSPeakListsDA", results, hash, cacheDB)
            }

            ret[[ana]][[gname]] <- results

            setTxtProgressBar(prog, grpi)
        }

        setTxtProgressBar(prog, gcount)
        close(prog)

        if (is.null(cachedSet))
            saveCacheSet("MSPeakListsDA", resultHashes[resultHashes != ""], setHash, cacheDB)
    }

    return(MSPeakLists(peakLists = ret, avgPeakListArgs = avgFGroupParams, algorithm = "Bruker_DataAnalysis"))
}

#' @details \code{generateDAFMFMSPeakLists} is similar to \code{generateDAMSPeakLists},
#'   but uses compounds that were generated by the Find Molecular Features (FMF)
#'   algorithm to extract MS peak lists. This is generally much faster than
#'   \code{generateDAMSPeakLists}, however, it only works when features were obtained
#'   using the \code{\link{findFeaturesBruker}} function. Since all MS spectra
#'   are generated in advance by Bruker DataAnalysis, no further parameters
#'   exist to customize its operation.
#'
#' @rdname MSPeakLists-generation
#' @export
generateDAFMFMSPeakLists <- function(fGroups, avgFGroupParams = getDefAvgPListParams())
{
    ac <- checkmate::makeAssertCollection()
    checkmate::assertClass(fGroups, "featureGroups", add = ac)
    assertAvgPListParams(avgFGroupParams, add = ac)
    checkmate::reportAssertions(ac)
    
    # UNDONE: implement topMost

    cacheDB <- openCacheDBScope()

    ftindex <- groupFeatIndex(fGroups)
    gcount <- ncol(ftindex)
    fTable <- featureTable(fGroups)
    anaInfo <- analysisInfo(fGroups)
    DA <- getDAApplication()

    hideDAInScope()

    # structure: [[analysis]][[fGroup]][[MSType]][[MSPeak]]
    ret <- list()

    for (anai in seq_len(nrow(anaInfo)))
    {
        ana <- anaInfo$analysis[anai]

        setHash <- makeHash(ana, anaInfo$path[anai])
        cachedSet <- loadCacheSet("MSPeakListsDAFMF", setHash, cacheDB)
        resultHashes <- vector("character", gcount)

        findDA <- getDAFileIndex(DA, ana, anaInfo$path[anai])

        cmpds <- DA[["Analyses"]][[findDA]][["Compounds"]]

        if (is.null(cachedSet))
        {
            cat("Deconvoluting spectra ...")
            cmpds$Deconvolute()
            cat("Done!\n")
        }

        printf("Loading all MS peak lists for %d feature groups in analysis '%s'...\n", gcount, ana)
        prog <- txtProgressBar(0, gcount, style=3)

        for (grpi in seq_len(gcount))
        {
            fti <- ftindex[[grpi]][anai]
            if (fti == 0)
                next

            gname <- colnames(ftindex)[grpi]

            hash <- makeHash(setHash, gname)
            resultHashes[grpi] <- hash

            results <- NULL
            if (!is.null(cachedSet))
                results <- cachedSet[[hash]]
            if (is.null(results))
                results <- loadCacheData("MSPeakListsDAFMF", hash, cacheDB)

            if (is.null(results))
            {
                results <- list()

                results$MS <- getDAPeakList(findDA, fti, TRUE, FALSE)

                if (cmpds[[fti]]$Count() > 1)
                    results$MSMS <- getDAPeakList(findDA, fti, TRUE, TRUE)

                saveCacheData("MSPeakListsDAFMF", results, hash, cacheDB)
            }

            ret[[ana]][[gname]] <- results

            setTxtProgressBar(prog, grpi)
        }

        setTxtProgressBar(prog, gcount)
        close(prog)

        if (is.null(cachedSet))
            saveCacheSet("MSPeakListsDAFMF", resultHashes[resultHashes != ""], setHash, cacheDB)
    }

    return(MSPeakLists(peakLists = ret, avgPeakListArgs = avgFGroupParams, algorithm = "Bruker_DataAnalysis_FMF"))
}
