# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

writeTraML <- function(IDs, out) {
    invisible(.Call(`_patRoon_writeTraML`, IDs, out))
}

writeChromsToMzML <- function(EICs, IDs, out) {
    invisible(.Call(`_patRoon_writeChromsToMzML`, EICs, IDs, out))
}

initBrukerLibrary <- function(path, force = FALSE) {
    .Call(`_patRoon_initBrukerLibrary`, path, force)
}

getBrukerCCS <- function(mobs, charges, mzs) {
    .Call(`_patRoon_getBrukerCCS`, mobs, charges, mzs)
}

getBrukerMob <- function(ccss, charges, mzs) {
    .Call(`_patRoon_getBrukerMob`, ccss, charges, mzs)
}

backendAvailable <- function(b) {
    .Call(`_patRoon_backendAvailable`, b)
}

walkSpectra <- function(backend) {
    .Call(`_patRoon_walkSpectra`, backend)
}

getMSSpectrum <- function(backend, index, MSLevel, frameIndex = -1L) {
    .Call(`_patRoon_getMSSpectrum`, backend, index, MSLevel, frameIndex)
}

getCentroidedFrame <- function(backend, index, mzWindow, mobWindow, minIntensity, method) {
    .Call(`_patRoon_getCentroidedFrame`, backend, index, mzWindow, mobWindow, minIntensity, method)
}

getScans <- function(backend, timeStart, timeEnd, MSLevel, prec) {
    .Call(`_patRoon_getScans`, backend, timeStart, timeEnd, MSLevel, prec)
}

getEICList <- function(backend, startMZs, endMZs, startTimes, endTimes, startMobs, endMobs, minIntensityIMS, compress, withBP = FALSE) {
    .Call(`_patRoon_getEICList`, backend, startMZs, endMZs, startTimes, endTimes, startMobs, endMobs, minIntensityIMS, compress, withBP)
}

getMSMetadata <- function(backend, msLevel) {
    .Call(`_patRoon_getMSMetadata`, backend, msLevel)
}

setSpecMetadata <- function(backend, mdMS, mdMSMS) {
    invisible(.Call(`_patRoon_setSpecMetadata`, backend, mdMS, mdMSMS))
}

getMSPeakLists <- function(backend, startTimes, endTimes, precursorMZs, withPrecursor, retainPrecursor, MSLevel, method, mzWindow, startMobs, endMobs, minAbundance, topMost, minIntensityIMS, minIntensityPre, minIntensityPost, minBPIntensity) {
    .Call(`_patRoon_getMSPeakLists`, backend, startTimes, endTimes, precursorMZs, withPrecursor, retainPrecursor, MSLevel, method, mzWindow, startMobs, endMobs, minAbundance, topMost, minIntensityIMS, minIntensityPre, minIntensityPost, minBPIntensity)
}

getEIMList <- function(backend, startMZs, endMZs, startTimes, endTimes, startMobs, endMobs, method, mobWindow, minIntensity, compress) {
    .Call(`_patRoon_getEIMList`, backend, startMZs, endMZs, startTimes, endTimes, startMobs, endMobs, method, mobWindow, minIntensity, compress)
}

getPeakIntensities <- function(backend, startMZs, endMZs, times) {
    .Call(`_patRoon_getPeakIntensities`, backend, startMZs, endMZs, times)
}

collapseIMSFrames <- function(backend, mzStart, mzEnd, mobilityStart, mobilityEnd, method, mzWindow, minAbundance, topMost, minIntensityIMS, minIntensityPre) {
    .Call(`_patRoon_collapseIMSFrames`, backend, mzStart, mzEnd, mobilityStart, mobilityEnd, method, mzWindow, minAbundance, topMost, minIntensityIMS, minIntensityPre)
}

testMS1Writer <- function(backend, out, mzStart, mzEnd, mobilityStart, mobilityEnd, method, mzWindow, minAbundance, topMost, minIntensityIMS, minIntensityPre) {
    invisible(.Call(`_patRoon_testMS1Writer`, backend, out, mzStart, mzEnd, mobilityStart, mobilityEnd, method, mzWindow, minAbundance, topMost, minIntensityIMS, minIntensityPre))
}

readMSP <- function(file, pc) {
    .Call(`_patRoon_readMSP`, file, pc)
}

writeMSPLibrary <- function(recordsM, spectraList, outCV) {
    invisible(.Call(`_patRoon_writeMSPLibrary`, recordsM, spectraList, outCV))
}

readMoNAJSON <- function(file) {
    .Call(`_patRoon_readMoNAJSON`, file)
}

parseAdductConsXMLFile <- function(file) {
    .Call(`_patRoon_parseAdductConsXMLFile`, file)
}

parseFeatureXMLFile <- function(file) {
    .Call(`_patRoon_parseFeatureXMLFile`, file)
}

parseFeatureMRMXMLFile <- function(file) {
    .Call(`_patRoon_parseFeatureMRMXMLFile`, file)
}

parseFeatConsXMLFile <- function(file, anaCount) {
    .Call(`_patRoon_parseFeatConsXMLFile`, file, anaCount)
}

writeFeatureXML <- function(featList, fPath, out, hulls) {
    invisible(.Call(`_patRoon_writeFeatureXML`, featList, fPath, out, hulls))
}

doFindPeaksDietrich <- function(EICs, minIntensity, SN, peakWidthMin, peakWidthMax, RTMin, RTMax, maxPeaksPerSignal, verbose = TRUE) {
    .Call(`_patRoon_doFindPeaksDietrich`, EICs, minIntensity, SN, peakWidthMin, peakWidthMax, RTMin, RTMax, maxPeaksPerSignal, verbose)
}

specDistMatrix <- function(specList, method, shift, precMZs, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistMatrix`, specList, method, shift, precMZs, mzWeight, intWeight, mzWindow)
}

specDistRect <- function(specList1, specList2, method, shift, precMZs1, precMZs2, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistRect`, specList1, specList2, method, shift, precMZs1, precMZs2, mzWeight, intWeight, mzWindow)
}

testSpecFilter <- function(mzs, ints, mzMin, mzMax, minInt, topMost, prec) {
    .Call(`_patRoon_testSpecFilter`, mzs, ints, mzMin, mzMax, minInt, topMost, prec)
}

testClusterNums <- function(nums, method, window) {
    .Call(`_patRoon_testClusterNums`, nums, method, window)
}

testClusterNums2 <- function(nums, method, window) {
    .Call(`_patRoon_testClusterNums2`, nums, method, window)
}

doAverageSpectra <- function(specs, method, window, minIntensity, minAbundance) {
    .Call(`_patRoon_doAverageSpectra`, specs, method, window, minIntensity, minAbundance)
}

doAverageSpectraList <- function(specsList, method, window, minIntensity, minAbundance) {
    .Call(`_patRoon_doAverageSpectraList`, specsList, method, window, minIntensity, minAbundance)
}

loadEICIntensities <- function(spectra, featList, rtWindow) {
    .Call(`_patRoon_loadEICIntensities`, spectra, featList, rtWindow)
}

loadEICs <- function(spectra, rtMins, rtMaxs, mzMins, mzMaxs) {
    .Call(`_patRoon_loadEICs`, spectra, rtMins, rtMaxs, mzMins, mzMaxs)
}

makeSAFDInput <- function(spectra, mzRange) {
    .Call(`_patRoon_makeSAFDInput`, spectra, mzRange)
}

binSpectra <- function(sp1, sp2, shift, precDiff, mzWindow) {
    .Call(`_patRoon_binSpectra`, sp1, sp2, shift, precDiff, mzWindow)
}

calcSpecSimilarity <- function(sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_calcSpecSimilarity`, sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow)
}

calcAnnSims <- function(spectrum, annotatedInds, method, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_calcAnnSims`, spectrum, annotatedInds, method, mzWeight, intWeight, mzWindow)
}

addFilesToOpenMSIni <- function(file, inFiles, outFiles) {
    invisible(.Call(`_patRoon_addFilesToOpenMSIni`, file, inFiles, outFiles))
}

loadAgilentIMSCalibration <- function(file) {
    .Call(`_patRoon_loadAgilentIMSCalibration`, file)
}

getOMPMaxNumThreads <- function() {
    .Call(`_patRoon_getOMPMaxNumThreads`)
}

setOMPNumThreads <- function(n) {
    invisible(.Call(`_patRoon_setOMPNumThreads`, n))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_patRoon_RcppExport_registerCCallable`)
})
