# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readMSP <- function(file, pc) {
    .Call(`_patRoon_readMSP`, file, pc)
}

writeMSPLibrary <- function(recordsM, spectraList, outCV) {
    invisible(.Call(`_patRoon_writeMSPLibrary`, recordsM, spectraList, outCV))
}

readMoNAJSON <- function(file) {
    .Call(`_patRoon_readMoNAJSON`, file)
}

parseAdductConsXMLFile <- function(file) {
    .Call(`_patRoon_parseAdductConsXMLFile`, file)
}

parseFeatureXMLFile <- function(file) {
    .Call(`_patRoon_parseFeatureXMLFile`, file)
}

parseFeatConsXMLFile <- function(file, anaCount) {
    .Call(`_patRoon_parseFeatConsXMLFile`, file, anaCount)
}

writeFeatureXML <- function(featList, fPath, out, hulls) {
    invisible(.Call(`_patRoon_writeFeatureXML`, featList, fPath, out, hulls))
}

specDistMatrix <- function(specList, method, shift, precMZs, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistMatrix`, specList, method, shift, precMZs, mzWeight, intWeight, mzWindow)
}

specDistRect <- function(specList1, specList2, method, shift, precMZs1, precMZs2, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistRect`, specList1, specList2, method, shift, precMZs1, precMZs2, mzWeight, intWeight, mzWindow)
}

initBrukerLibrary <- function(path) {
    invisible(.Call(`_patRoon_initBrukerLibrary`, path))
}

collapseTIMSFrame <- function(file, frameID, method, mzWindow, topMost = 0L, minIntensity = 0L, scanStart = 0L, scanEnd = 0L) {
    .Call(`_patRoon_collapseTIMSFrame`, file, frameID, method, mzWindow, topMost, minIntensity, scanStart, scanEnd)
}

getTIMSPeakLists <- function(file, frameIDsList, scanStartsList, scanEndsList, mobilityStarts, mobilityEnds, method, mzWindow, topMost = 0L, minIntensityPre = 0L, minIntensityPost = 0L) {
    .Call(`_patRoon_getTIMSPeakLists`, file, frameIDsList, scanStartsList, scanEndsList, mobilityStarts, mobilityEnds, method, mzWindow, topMost, minIntensityPre, minIntensityPost)
}

getTIMSEIC <- function(file, frameIDs, mzStarts, mzEnds, mobilityStarts, mobilityEnds) {
    .Call(`_patRoon_getTIMSEIC`, file, frameIDs, mzStarts, mzEnds, mobilityStarts, mobilityEnds)
}

getTIMSMobilogram <- function(file, frameIDsList, mzStarts, mzEnds, method, IMSWindow, topMost = 0L, minIntensityPre = 0L, minIntensityPost = 0L) {
    .Call(`_patRoon_getTIMSMobilogram`, file, frameIDsList, mzStarts, mzEnds, method, IMSWindow, topMost, minIntensityPre, minIntensityPost)
}

collapseTIMSSpectra <- function(file, frameIDs, mzStart, mzEnd, mobilityStart, mobilityEnd, method, mzWindow, topMost, minIntensityPre, minIntensityPost) {
    .Call(`_patRoon_collapseTIMSSpectra`, file, frameIDs, mzStart, mzEnd, mobilityStart, mobilityEnd, method, mzWindow, topMost, minIntensityPre, minIntensityPost)
}

loadEICIntensities <- function(spectra, featList, rtWindow) {
    .Call(`_patRoon_loadEICIntensities`, spectra, featList, rtWindow)
}

loadEICs <- function(spectra, rtMins, rtMaxs, mzMins, mzMaxs) {
    .Call(`_patRoon_loadEICs`, spectra, rtMins, rtMaxs, mzMins, mzMaxs)
}

makeSAFDInput <- function(spectra, mzRange) {
    .Call(`_patRoon_makeSAFDInput`, spectra, mzRange)
}

binSpectra <- function(sp1, sp2, shift, precDiff, mzWindow) {
    .Call(`_patRoon_binSpectra`, sp1, sp2, shift, precDiff, mzWindow)
}

calcSpecSimilarity <- function(sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_calcSpecSimilarity`, sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow)
}

addFilesToOpenMSIni <- function(file, inFiles, outFiles) {
    invisible(.Call(`_patRoon_addFilesToOpenMSIni`, file, inFiles, outFiles))
}

