# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readMSP <- function(file, pc) {
    .Call(`_patRoon_readMSP`, file, pc)
}

writeMSPLibrary <- function(recordsM, spectraList, outCV) {
    invisible(.Call(`_patRoon_writeMSPLibrary`, recordsM, spectraList, outCV))
}

parseAdductConsXMLFile <- function(file) {
    .Call(`_patRoon_parseAdductConsXMLFile`, file)
}

parseFeatureXMLFile <- function(file) {
    .Call(`_patRoon_parseFeatureXMLFile`, file)
}

parseFeatConsXMLFile <- function(file, anaCount) {
    .Call(`_patRoon_parseFeatConsXMLFile`, file, anaCount)
}

writeFeatureXML <- function(featList, out, hulls) {
    invisible(.Call(`_patRoon_writeFeatureXML`, featList, out, hulls))
}

specDistMatrix <- function(specList, method, shift, precMZs, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistMatrix`, specList, method, shift, precMZs, mzWeight, intWeight, mzWindow)
}

specDistRect <- function(specList1, specList2, method, shift, precMZs1, precMZs2, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistRect`, specList1, specList2, method, shift, precMZs1, precMZs2, mzWeight, intWeight, mzWindow)
}

loadEICIntensities <- function(spectra, featList, rtWindow) {
    .Call(`_patRoon_loadEICIntensities`, spectra, featList, rtWindow)
}

loadEICs <- function(spectra, rtMins, rtMaxs, mzMins, mzMaxs) {
    .Call(`_patRoon_loadEICs`, spectra, rtMins, rtMaxs, mzMins, mzMaxs)
}

makeSAFDInput <- function(spectra, mzRange) {
    .Call(`_patRoon_makeSAFDInput`, spectra, mzRange)
}

binSpectra <- function(sp1, sp2, shift, precDiff, mzWindow) {
    .Call(`_patRoon_binSpectra`, sp1, sp2, shift, precDiff, mzWindow)
}

calcSpecSimilarity <- function(sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_calcSpecSimilarity`, sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow)
}

